// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/folsomintel/fuse/internal/entspike/ent/host"
	"github.com/folsomintel/fuse/internal/entspike/ent/predicate"
)

// HostUpdate is the builder for updating Host entities.
type HostUpdate struct {
	config
	hooks    []Hook
	mutation *HostMutation
}

// Where appends a list predicates to the HostUpdate builder.
func (_u *HostUpdate) Where(ps ...predicate.Host) *HostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetURL sets the "url" field.
func (_u *HostUpdate) SetURL(v string) *HostUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HostUpdate) SetNillableURL(v *string) *HostUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (_u *HostUpdate) SetTokenEncrypted(v []byte) *HostUpdate {
	_u.mutation.SetTokenEncrypted(v)
	return _u
}

// ClearTokenEncrypted clears the value of the "token_encrypted" field.
func (_u *HostUpdate) ClearTokenEncrypted() *HostUpdate {
	_u.mutation.ClearTokenEncrypted()
	return _u
}

// SetRegion sets the "region" field.
func (_u *HostUpdate) SetRegion(v string) *HostUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *HostUpdate) SetNillableRegion(v *string) *HostUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *HostUpdate) SetState(v host.State) *HostUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *HostUpdate) SetNillableState(v *host.State) *HostUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *HostUpdate) SetTenantID(v string) *HostUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *HostUpdate) SetNillableTenantID(v *string) *HostUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCpusTotal sets the "cpus_total" field.
func (_u *HostUpdate) SetCpusTotal(v int) *HostUpdate {
	_u.mutation.ResetCpusTotal()
	_u.mutation.SetCpusTotal(v)
	return _u
}

// SetNillableCpusTotal sets the "cpus_total" field if the given value is not nil.
func (_u *HostUpdate) SetNillableCpusTotal(v *int) *HostUpdate {
	if v != nil {
		_u.SetCpusTotal(*v)
	}
	return _u
}

// AddCpusTotal adds value to the "cpus_total" field.
func (_u *HostUpdate) AddCpusTotal(v int) *HostUpdate {
	_u.mutation.AddCpusTotal(v)
	return _u
}

// SetRAMMBTotal sets the "ram_mb_total" field.
func (_u *HostUpdate) SetRAMMBTotal(v int) *HostUpdate {
	_u.mutation.ResetRAMMBTotal()
	_u.mutation.SetRAMMBTotal(v)
	return _u
}

// SetNillableRAMMBTotal sets the "ram_mb_total" field if the given value is not nil.
func (_u *HostUpdate) SetNillableRAMMBTotal(v *int) *HostUpdate {
	if v != nil {
		_u.SetRAMMBTotal(*v)
	}
	return _u
}

// AddRAMMBTotal adds value to the "ram_mb_total" field.
func (_u *HostUpdate) AddRAMMBTotal(v int) *HostUpdate {
	_u.mutation.AddRAMMBTotal(v)
	return _u
}

// SetStorageGBTotal sets the "storage_gb_total" field.
func (_u *HostUpdate) SetStorageGBTotal(v int) *HostUpdate {
	_u.mutation.ResetStorageGBTotal()
	_u.mutation.SetStorageGBTotal(v)
	return _u
}

// SetNillableStorageGBTotal sets the "storage_gb_total" field if the given value is not nil.
func (_u *HostUpdate) SetNillableStorageGBTotal(v *int) *HostUpdate {
	if v != nil {
		_u.SetStorageGBTotal(*v)
	}
	return _u
}

// AddStorageGBTotal adds value to the "storage_gb_total" field.
func (_u *HostUpdate) AddStorageGBTotal(v int) *HostUpdate {
	_u.mutation.AddStorageGBTotal(v)
	return _u
}

// SetVMCountMax sets the "vm_count_max" field.
func (_u *HostUpdate) SetVMCountMax(v int) *HostUpdate {
	_u.mutation.ResetVMCountMax()
	_u.mutation.SetVMCountMax(v)
	return _u
}

// SetNillableVMCountMax sets the "vm_count_max" field if the given value is not nil.
func (_u *HostUpdate) SetNillableVMCountMax(v *int) *HostUpdate {
	if v != nil {
		_u.SetVMCountMax(*v)
	}
	return _u
}

// AddVMCountMax adds value to the "vm_count_max" field.
func (_u *HostUpdate) AddVMCountMax(v int) *HostUpdate {
	_u.mutation.AddVMCountMax(v)
	return _u
}

// SetCpusAllocated sets the "cpus_allocated" field.
func (_u *HostUpdate) SetCpusAllocated(v int) *HostUpdate {
	_u.mutation.ResetCpusAllocated()
	_u.mutation.SetCpusAllocated(v)
	return _u
}

// SetNillableCpusAllocated sets the "cpus_allocated" field if the given value is not nil.
func (_u *HostUpdate) SetNillableCpusAllocated(v *int) *HostUpdate {
	if v != nil {
		_u.SetCpusAllocated(*v)
	}
	return _u
}

// AddCpusAllocated adds value to the "cpus_allocated" field.
func (_u *HostUpdate) AddCpusAllocated(v int) *HostUpdate {
	_u.mutation.AddCpusAllocated(v)
	return _u
}

// SetRAMMBAllocated sets the "ram_mb_allocated" field.
func (_u *HostUpdate) SetRAMMBAllocated(v int) *HostUpdate {
	_u.mutation.ResetRAMMBAllocated()
	_u.mutation.SetRAMMBAllocated(v)
	return _u
}

// SetNillableRAMMBAllocated sets the "ram_mb_allocated" field if the given value is not nil.
func (_u *HostUpdate) SetNillableRAMMBAllocated(v *int) *HostUpdate {
	if v != nil {
		_u.SetRAMMBAllocated(*v)
	}
	return _u
}

// AddRAMMBAllocated adds value to the "ram_mb_allocated" field.
func (_u *HostUpdate) AddRAMMBAllocated(v int) *HostUpdate {
	_u.mutation.AddRAMMBAllocated(v)
	return _u
}

// SetStorageGBAllocated sets the "storage_gb_allocated" field.
func (_u *HostUpdate) SetStorageGBAllocated(v int) *HostUpdate {
	_u.mutation.ResetStorageGBAllocated()
	_u.mutation.SetStorageGBAllocated(v)
	return _u
}

// SetNillableStorageGBAllocated sets the "storage_gb_allocated" field if the given value is not nil.
func (_u *HostUpdate) SetNillableStorageGBAllocated(v *int) *HostUpdate {
	if v != nil {
		_u.SetStorageGBAllocated(*v)
	}
	return _u
}

// AddStorageGBAllocated adds value to the "storage_gb_allocated" field.
func (_u *HostUpdate) AddStorageGBAllocated(v int) *HostUpdate {
	_u.mutation.AddStorageGBAllocated(v)
	return _u
}

// SetVMCountAllocated sets the "vm_count_allocated" field.
func (_u *HostUpdate) SetVMCountAllocated(v int) *HostUpdate {
	_u.mutation.ResetVMCountAllocated()
	_u.mutation.SetVMCountAllocated(v)
	return _u
}

// SetNillableVMCountAllocated sets the "vm_count_allocated" field if the given value is not nil.
func (_u *HostUpdate) SetNillableVMCountAllocated(v *int) *HostUpdate {
	if v != nil {
		_u.SetVMCountAllocated(*v)
	}
	return _u
}

// AddVMCountAllocated adds value to the "vm_count_allocated" field.
func (_u *HostUpdate) AddVMCountAllocated(v int) *HostUpdate {
	_u.mutation.AddVMCountAllocated(v)
	return _u
}

// SetLabels sets the "labels" field.
func (_u *HostUpdate) SetLabels(v map[string]string) *HostUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// SetArch sets the "arch" field.
func (_u *HostUpdate) SetArch(v string) *HostUpdate {
	_u.mutation.SetArch(v)
	return _u
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (_u *HostUpdate) SetNillableArch(v *string) *HostUpdate {
	if v != nil {
		_u.SetArch(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *HostUpdate) SetLastSeenAt(v time.Time) *HostUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *HostUpdate) SetNillableLastSeenAt(v *time.Time) *HostUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HostUpdate) SetUpdatedAt(v time.Time) *HostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the HostMutation object of the builder.
func (_u *HostUpdate) Mutation() *HostMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := host.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HostUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := host.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Host.state": %w`, err)}
		}
	}
	return nil
}

func (_u *HostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(host.Table, host.Columns, sqlgraph.NewFieldSpec(host.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(host.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenEncrypted(); ok {
		_spec.SetField(host.FieldTokenEncrypted, field.TypeBytes, value)
	}
	if _u.mutation.TokenEncryptedCleared() {
		_spec.ClearField(host.FieldTokenEncrypted, field.TypeBytes)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(host.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(host.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(host.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CpusTotal(); ok {
		_spec.SetField(host.FieldCpusTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCpusTotal(); ok {
		_spec.AddField(host.FieldCpusTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RAMMBTotal(); ok {
		_spec.SetField(host.FieldRAMMBTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRAMMBTotal(); ok {
		_spec.AddField(host.FieldRAMMBTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StorageGBTotal(); ok {
		_spec.SetField(host.FieldStorageGBTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStorageGBTotal(); ok {
		_spec.AddField(host.FieldStorageGBTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VMCountMax(); ok {
		_spec.SetField(host.FieldVMCountMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVMCountMax(); ok {
		_spec.AddField(host.FieldVMCountMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CpusAllocated(); ok {
		_spec.SetField(host.FieldCpusAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCpusAllocated(); ok {
		_spec.AddField(host.FieldCpusAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RAMMBAllocated(); ok {
		_spec.SetField(host.FieldRAMMBAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRAMMBAllocated(); ok {
		_spec.AddField(host.FieldRAMMBAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StorageGBAllocated(); ok {
		_spec.SetField(host.FieldStorageGBAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStorageGBAllocated(); ok {
		_spec.AddField(host.FieldStorageGBAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VMCountAllocated(); ok {
		_spec.SetField(host.FieldVMCountAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVMCountAllocated(); ok {
		_spec.AddField(host.FieldVMCountAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(host.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Arch(); ok {
		_spec.SetField(host.FieldArch, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(host.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(host.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{host.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HostUpdateOne is the builder for updating a single Host entity.
type HostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HostMutation
}

// SetURL sets the "url" field.
func (_u *HostUpdateOne) SetURL(v string) *HostUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableURL(v *string) *HostUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (_u *HostUpdateOne) SetTokenEncrypted(v []byte) *HostUpdateOne {
	_u.mutation.SetTokenEncrypted(v)
	return _u
}

// ClearTokenEncrypted clears the value of the "token_encrypted" field.
func (_u *HostUpdateOne) ClearTokenEncrypted() *HostUpdateOne {
	_u.mutation.ClearTokenEncrypted()
	return _u
}

// SetRegion sets the "region" field.
func (_u *HostUpdateOne) SetRegion(v string) *HostUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableRegion(v *string) *HostUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *HostUpdateOne) SetState(v host.State) *HostUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableState(v *host.State) *HostUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *HostUpdateOne) SetTenantID(v string) *HostUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableTenantID(v *string) *HostUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCpusTotal sets the "cpus_total" field.
func (_u *HostUpdateOne) SetCpusTotal(v int) *HostUpdateOne {
	_u.mutation.ResetCpusTotal()
	_u.mutation.SetCpusTotal(v)
	return _u
}

// SetNillableCpusTotal sets the "cpus_total" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableCpusTotal(v *int) *HostUpdateOne {
	if v != nil {
		_u.SetCpusTotal(*v)
	}
	return _u
}

// AddCpusTotal adds value to the "cpus_total" field.
func (_u *HostUpdateOne) AddCpusTotal(v int) *HostUpdateOne {
	_u.mutation.AddCpusTotal(v)
	return _u
}

// SetRAMMBTotal sets the "ram_mb_total" field.
func (_u *HostUpdateOne) SetRAMMBTotal(v int) *HostUpdateOne {
	_u.mutation.ResetRAMMBTotal()
	_u.mutation.SetRAMMBTotal(v)
	return _u
}

// SetNillableRAMMBTotal sets the "ram_mb_total" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableRAMMBTotal(v *int) *HostUpdateOne {
	if v != nil {
		_u.SetRAMMBTotal(*v)
	}
	return _u
}

// AddRAMMBTotal adds value to the "ram_mb_total" field.
func (_u *HostUpdateOne) AddRAMMBTotal(v int) *HostUpdateOne {
	_u.mutation.AddRAMMBTotal(v)
	return _u
}

// SetStorageGBTotal sets the "storage_gb_total" field.
func (_u *HostUpdateOne) SetStorageGBTotal(v int) *HostUpdateOne {
	_u.mutation.ResetStorageGBTotal()
	_u.mutation.SetStorageGBTotal(v)
	return _u
}

// SetNillableStorageGBTotal sets the "storage_gb_total" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableStorageGBTotal(v *int) *HostUpdateOne {
	if v != nil {
		_u.SetStorageGBTotal(*v)
	}
	return _u
}

// AddStorageGBTotal adds value to the "storage_gb_total" field.
func (_u *HostUpdateOne) AddStorageGBTotal(v int) *HostUpdateOne {
	_u.mutation.AddStorageGBTotal(v)
	return _u
}

// SetVMCountMax sets the "vm_count_max" field.
func (_u *HostUpdateOne) SetVMCountMax(v int) *HostUpdateOne {
	_u.mutation.ResetVMCountMax()
	_u.mutation.SetVMCountMax(v)
	return _u
}

// SetNillableVMCountMax sets the "vm_count_max" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableVMCountMax(v *int) *HostUpdateOne {
	if v != nil {
		_u.SetVMCountMax(*v)
	}
	return _u
}

// AddVMCountMax adds value to the "vm_count_max" field.
func (_u *HostUpdateOne) AddVMCountMax(v int) *HostUpdateOne {
	_u.mutation.AddVMCountMax(v)
	return _u
}

// SetCpusAllocated sets the "cpus_allocated" field.
func (_u *HostUpdateOne) SetCpusAllocated(v int) *HostUpdateOne {
	_u.mutation.ResetCpusAllocated()
	_u.mutation.SetCpusAllocated(v)
	return _u
}

// SetNillableCpusAllocated sets the "cpus_allocated" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableCpusAllocated(v *int) *HostUpdateOne {
	if v != nil {
		_u.SetCpusAllocated(*v)
	}
	return _u
}

// AddCpusAllocated adds value to the "cpus_allocated" field.
func (_u *HostUpdateOne) AddCpusAllocated(v int) *HostUpdateOne {
	_u.mutation.AddCpusAllocated(v)
	return _u
}

// SetRAMMBAllocated sets the "ram_mb_allocated" field.
func (_u *HostUpdateOne) SetRAMMBAllocated(v int) *HostUpdateOne {
	_u.mutation.ResetRAMMBAllocated()
	_u.mutation.SetRAMMBAllocated(v)
	return _u
}

// SetNillableRAMMBAllocated sets the "ram_mb_allocated" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableRAMMBAllocated(v *int) *HostUpdateOne {
	if v != nil {
		_u.SetRAMMBAllocated(*v)
	}
	return _u
}

// AddRAMMBAllocated adds value to the "ram_mb_allocated" field.
func (_u *HostUpdateOne) AddRAMMBAllocated(v int) *HostUpdateOne {
	_u.mutation.AddRAMMBAllocated(v)
	return _u
}

// SetStorageGBAllocated sets the "storage_gb_allocated" field.
func (_u *HostUpdateOne) SetStorageGBAllocated(v int) *HostUpdateOne {
	_u.mutation.ResetStorageGBAllocated()
	_u.mutation.SetStorageGBAllocated(v)
	return _u
}

// SetNillableStorageGBAllocated sets the "storage_gb_allocated" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableStorageGBAllocated(v *int) *HostUpdateOne {
	if v != nil {
		_u.SetStorageGBAllocated(*v)
	}
	return _u
}

// AddStorageGBAllocated adds value to the "storage_gb_allocated" field.
func (_u *HostUpdateOne) AddStorageGBAllocated(v int) *HostUpdateOne {
	_u.mutation.AddStorageGBAllocated(v)
	return _u
}

// SetVMCountAllocated sets the "vm_count_allocated" field.
func (_u *HostUpdateOne) SetVMCountAllocated(v int) *HostUpdateOne {
	_u.mutation.ResetVMCountAllocated()
	_u.mutation.SetVMCountAllocated(v)
	return _u
}

// SetNillableVMCountAllocated sets the "vm_count_allocated" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableVMCountAllocated(v *int) *HostUpdateOne {
	if v != nil {
		_u.SetVMCountAllocated(*v)
	}
	return _u
}

// AddVMCountAllocated adds value to the "vm_count_allocated" field.
func (_u *HostUpdateOne) AddVMCountAllocated(v int) *HostUpdateOne {
	_u.mutation.AddVMCountAllocated(v)
	return _u
}

// SetLabels sets the "labels" field.
func (_u *HostUpdateOne) SetLabels(v map[string]string) *HostUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// SetArch sets the "arch" field.
func (_u *HostUpdateOne) SetArch(v string) *HostUpdateOne {
	_u.mutation.SetArch(v)
	return _u
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableArch(v *string) *HostUpdateOne {
	if v != nil {
		_u.SetArch(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *HostUpdateOne) SetLastSeenAt(v time.Time) *HostUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *HostUpdateOne) SetNillableLastSeenAt(v *time.Time) *HostUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HostUpdateOne) SetUpdatedAt(v time.Time) *HostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the HostMutation object of the builder.
func (_u *HostUpdateOne) Mutation() *HostMutation {
	return _u.mutation
}

// Where appends a list predicates to the HostUpdate builder.
func (_u *HostUpdateOne) Where(ps ...predicate.Host) *HostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HostUpdateOne) Select(field string, fields ...string) *HostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Host entity.
func (_u *HostUpdateOne) Save(ctx context.Context) (*Host, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HostUpdateOne) SaveX(ctx context.Context) *Host {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := host.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HostUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := host.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Host.state": %w`, err)}
		}
	}
	return nil
}

func (_u *HostUpdateOne) sqlSave(ctx context.Context) (_node *Host, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(host.Table, host.Columns, sqlgraph.NewFieldSpec(host.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Host.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, host.FieldID)
		for _, f := range fields {
			if !host.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != host.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(host.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenEncrypted(); ok {
		_spec.SetField(host.FieldTokenEncrypted, field.TypeBytes, value)
	}
	if _u.mutation.TokenEncryptedCleared() {
		_spec.ClearField(host.FieldTokenEncrypted, field.TypeBytes)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(host.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(host.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(host.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CpusTotal(); ok {
		_spec.SetField(host.FieldCpusTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCpusTotal(); ok {
		_spec.AddField(host.FieldCpusTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RAMMBTotal(); ok {
		_spec.SetField(host.FieldRAMMBTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRAMMBTotal(); ok {
		_spec.AddField(host.FieldRAMMBTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StorageGBTotal(); ok {
		_spec.SetField(host.FieldStorageGBTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStorageGBTotal(); ok {
		_spec.AddField(host.FieldStorageGBTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VMCountMax(); ok {
		_spec.SetField(host.FieldVMCountMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVMCountMax(); ok {
		_spec.AddField(host.FieldVMCountMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CpusAllocated(); ok {
		_spec.SetField(host.FieldCpusAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCpusAllocated(); ok {
		_spec.AddField(host.FieldCpusAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RAMMBAllocated(); ok {
		_spec.SetField(host.FieldRAMMBAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRAMMBAllocated(); ok {
		_spec.AddField(host.FieldRAMMBAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StorageGBAllocated(); ok {
		_spec.SetField(host.FieldStorageGBAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStorageGBAllocated(); ok {
		_spec.AddField(host.FieldStorageGBAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VMCountAllocated(); ok {
		_spec.SetField(host.FieldVMCountAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVMCountAllocated(); ok {
		_spec.AddField(host.FieldVMCountAllocated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(host.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Arch(); ok {
		_spec.SetField(host.FieldArch, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(host.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(host.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Host{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{host.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
