// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/folsomintel/fuse/internal/entspike/ent/host"
)

// HostCreate is the builder for creating a Host entity.
type HostCreate struct {
	config
	mutation *HostMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetURL sets the "url" field.
func (_c *HostCreate) SetURL(v string) *HostCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (_c *HostCreate) SetTokenEncrypted(v []byte) *HostCreate {
	_c.mutation.SetTokenEncrypted(v)
	return _c
}

// SetRegion sets the "region" field.
func (_c *HostCreate) SetRegion(v string) *HostCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *HostCreate) SetNillableRegion(v *string) *HostCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *HostCreate) SetState(v host.State) *HostCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *HostCreate) SetNillableState(v *host.State) *HostCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *HostCreate) SetTenantID(v string) *HostCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *HostCreate) SetNillableTenantID(v *string) *HostCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCpusTotal sets the "cpus_total" field.
func (_c *HostCreate) SetCpusTotal(v int) *HostCreate {
	_c.mutation.SetCpusTotal(v)
	return _c
}

// SetNillableCpusTotal sets the "cpus_total" field if the given value is not nil.
func (_c *HostCreate) SetNillableCpusTotal(v *int) *HostCreate {
	if v != nil {
		_c.SetCpusTotal(*v)
	}
	return _c
}

// SetRAMMBTotal sets the "ram_mb_total" field.
func (_c *HostCreate) SetRAMMBTotal(v int) *HostCreate {
	_c.mutation.SetRAMMBTotal(v)
	return _c
}

// SetNillableRAMMBTotal sets the "ram_mb_total" field if the given value is not nil.
func (_c *HostCreate) SetNillableRAMMBTotal(v *int) *HostCreate {
	if v != nil {
		_c.SetRAMMBTotal(*v)
	}
	return _c
}

// SetStorageGBTotal sets the "storage_gb_total" field.
func (_c *HostCreate) SetStorageGBTotal(v int) *HostCreate {
	_c.mutation.SetStorageGBTotal(v)
	return _c
}

// SetNillableStorageGBTotal sets the "storage_gb_total" field if the given value is not nil.
func (_c *HostCreate) SetNillableStorageGBTotal(v *int) *HostCreate {
	if v != nil {
		_c.SetStorageGBTotal(*v)
	}
	return _c
}

// SetVMCountMax sets the "vm_count_max" field.
func (_c *HostCreate) SetVMCountMax(v int) *HostCreate {
	_c.mutation.SetVMCountMax(v)
	return _c
}

// SetNillableVMCountMax sets the "vm_count_max" field if the given value is not nil.
func (_c *HostCreate) SetNillableVMCountMax(v *int) *HostCreate {
	if v != nil {
		_c.SetVMCountMax(*v)
	}
	return _c
}

// SetCpusAllocated sets the "cpus_allocated" field.
func (_c *HostCreate) SetCpusAllocated(v int) *HostCreate {
	_c.mutation.SetCpusAllocated(v)
	return _c
}

// SetNillableCpusAllocated sets the "cpus_allocated" field if the given value is not nil.
func (_c *HostCreate) SetNillableCpusAllocated(v *int) *HostCreate {
	if v != nil {
		_c.SetCpusAllocated(*v)
	}
	return _c
}

// SetRAMMBAllocated sets the "ram_mb_allocated" field.
func (_c *HostCreate) SetRAMMBAllocated(v int) *HostCreate {
	_c.mutation.SetRAMMBAllocated(v)
	return _c
}

// SetNillableRAMMBAllocated sets the "ram_mb_allocated" field if the given value is not nil.
func (_c *HostCreate) SetNillableRAMMBAllocated(v *int) *HostCreate {
	if v != nil {
		_c.SetRAMMBAllocated(*v)
	}
	return _c
}

// SetStorageGBAllocated sets the "storage_gb_allocated" field.
func (_c *HostCreate) SetStorageGBAllocated(v int) *HostCreate {
	_c.mutation.SetStorageGBAllocated(v)
	return _c
}

// SetNillableStorageGBAllocated sets the "storage_gb_allocated" field if the given value is not nil.
func (_c *HostCreate) SetNillableStorageGBAllocated(v *int) *HostCreate {
	if v != nil {
		_c.SetStorageGBAllocated(*v)
	}
	return _c
}

// SetVMCountAllocated sets the "vm_count_allocated" field.
func (_c *HostCreate) SetVMCountAllocated(v int) *HostCreate {
	_c.mutation.SetVMCountAllocated(v)
	return _c
}

// SetNillableVMCountAllocated sets the "vm_count_allocated" field if the given value is not nil.
func (_c *HostCreate) SetNillableVMCountAllocated(v *int) *HostCreate {
	if v != nil {
		_c.SetVMCountAllocated(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *HostCreate) SetLabels(v map[string]string) *HostCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetArch sets the "arch" field.
func (_c *HostCreate) SetArch(v string) *HostCreate {
	_c.mutation.SetArch(v)
	return _c
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (_c *HostCreate) SetNillableArch(v *string) *HostCreate {
	if v != nil {
		_c.SetArch(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *HostCreate) SetLastSeenAt(v time.Time) *HostCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HostCreate) SetCreatedAt(v time.Time) *HostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HostCreate) SetNillableCreatedAt(v *time.Time) *HostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HostCreate) SetUpdatedAt(v time.Time) *HostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HostCreate) SetNillableUpdatedAt(v *time.Time) *HostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HostCreate) SetID(v string) *HostCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the HostMutation object of the builder.
func (_c *HostCreate) Mutation() *HostMutation {
	return _c.mutation
}

// Save creates the Host in the database.
func (_c *HostCreate) Save(ctx context.Context) (*Host, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HostCreate) SaveX(ctx context.Context) *Host {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HostCreate) defaults() {
	if _, ok := _c.mutation.Region(); !ok {
		v := host.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := host.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := host.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CpusTotal(); !ok {
		v := host.DefaultCpusTotal
		_c.mutation.SetCpusTotal(v)
	}
	if _, ok := _c.mutation.RAMMBTotal(); !ok {
		v := host.DefaultRAMMBTotal
		_c.mutation.SetRAMMBTotal(v)
	}
	if _, ok := _c.mutation.StorageGBTotal(); !ok {
		v := host.DefaultStorageGBTotal
		_c.mutation.SetStorageGBTotal(v)
	}
	if _, ok := _c.mutation.VMCountMax(); !ok {
		v := host.DefaultVMCountMax
		_c.mutation.SetVMCountMax(v)
	}
	if _, ok := _c.mutation.CpusAllocated(); !ok {
		v := host.DefaultCpusAllocated
		_c.mutation.SetCpusAllocated(v)
	}
	if _, ok := _c.mutation.RAMMBAllocated(); !ok {
		v := host.DefaultRAMMBAllocated
		_c.mutation.SetRAMMBAllocated(v)
	}
	if _, ok := _c.mutation.StorageGBAllocated(); !ok {
		v := host.DefaultStorageGBAllocated
		_c.mutation.SetStorageGBAllocated(v)
	}
	if _, ok := _c.mutation.VMCountAllocated(); !ok {
		v := host.DefaultVMCountAllocated
		_c.mutation.SetVMCountAllocated(v)
	}
	if _, ok := _c.mutation.Labels(); !ok {
		v := host.DefaultLabels
		_c.mutation.SetLabels(v)
	}
	if _, ok := _c.mutation.Arch(); !ok {
		v := host.DefaultArch
		_c.mutation.SetArch(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := host.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := host.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HostCreate) check() error {
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Host.url"`)}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "Host.region"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Host.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := host.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Host.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Host.tenant_id"`)}
	}
	if _, ok := _c.mutation.CpusTotal(); !ok {
		return &ValidationError{Name: "cpus_total", err: errors.New(`ent: missing required field "Host.cpus_total"`)}
	}
	if _, ok := _c.mutation.RAMMBTotal(); !ok {
		return &ValidationError{Name: "ram_mb_total", err: errors.New(`ent: missing required field "Host.ram_mb_total"`)}
	}
	if _, ok := _c.mutation.StorageGBTotal(); !ok {
		return &ValidationError{Name: "storage_gb_total", err: errors.New(`ent: missing required field "Host.storage_gb_total"`)}
	}
	if _, ok := _c.mutation.VMCountMax(); !ok {
		return &ValidationError{Name: "vm_count_max", err: errors.New(`ent: missing required field "Host.vm_count_max"`)}
	}
	if _, ok := _c.mutation.CpusAllocated(); !ok {
		return &ValidationError{Name: "cpus_allocated", err: errors.New(`ent: missing required field "Host.cpus_allocated"`)}
	}
	if _, ok := _c.mutation.RAMMBAllocated(); !ok {
		return &ValidationError{Name: "ram_mb_allocated", err: errors.New(`ent: missing required field "Host.ram_mb_allocated"`)}
	}
	if _, ok := _c.mutation.StorageGBAllocated(); !ok {
		return &ValidationError{Name: "storage_gb_allocated", err: errors.New(`ent: missing required field "Host.storage_gb_allocated"`)}
	}
	if _, ok := _c.mutation.VMCountAllocated(); !ok {
		return &ValidationError{Name: "vm_count_allocated", err: errors.New(`ent: missing required field "Host.vm_count_allocated"`)}
	}
	if _, ok := _c.mutation.Labels(); !ok {
		return &ValidationError{Name: "labels", err: errors.New(`ent: missing required field "Host.labels"`)}
	}
	if _, ok := _c.mutation.Arch(); !ok {
		return &ValidationError{Name: "arch", err: errors.New(`ent: missing required field "Host.arch"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "Host.last_seen_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Host.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Host.updated_at"`)}
	}
	return nil
}

func (_c *HostCreate) sqlSave(ctx context.Context) (*Host, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Host.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HostCreate) createSpec() (*Host, *sqlgraph.CreateSpec) {
	var (
		_node = &Host{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(host.Table, sqlgraph.NewFieldSpec(host.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(host.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.TokenEncrypted(); ok {
		_spec.SetField(host.FieldTokenEncrypted, field.TypeBytes, value)
		_node.TokenEncrypted = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(host.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(host.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(host.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CpusTotal(); ok {
		_spec.SetField(host.FieldCpusTotal, field.TypeInt, value)
		_node.CpusTotal = value
	}
	if value, ok := _c.mutation.RAMMBTotal(); ok {
		_spec.SetField(host.FieldRAMMBTotal, field.TypeInt, value)
		_node.RAMMBTotal = value
	}
	if value, ok := _c.mutation.StorageGBTotal(); ok {
		_spec.SetField(host.FieldStorageGBTotal, field.TypeInt, value)
		_node.StorageGBTotal = value
	}
	if value, ok := _c.mutation.VMCountMax(); ok {
		_spec.SetField(host.FieldVMCountMax, field.TypeInt, value)
		_node.VMCountMax = value
	}
	if value, ok := _c.mutation.CpusAllocated(); ok {
		_spec.SetField(host.FieldCpusAllocated, field.TypeInt, value)
		_node.CpusAllocated = value
	}
	if value, ok := _c.mutation.RAMMBAllocated(); ok {
		_spec.SetField(host.FieldRAMMBAllocated, field.TypeInt, value)
		_node.RAMMBAllocated = value
	}
	if value, ok := _c.mutation.StorageGBAllocated(); ok {
		_spec.SetField(host.FieldStorageGBAllocated, field.TypeInt, value)
		_node.StorageGBAllocated = value
	}
	if value, ok := _c.mutation.VMCountAllocated(); ok {
		_spec.SetField(host.FieldVMCountAllocated, field.TypeInt, value)
		_node.VMCountAllocated = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(host.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Arch(); ok {
		_spec.SetField(host.FieldArch, field.TypeString, value)
		_node.Arch = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(host.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(host.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(host.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Host.Create().
//		SetURL(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HostUpsert) {
//			SetURL(v+v).
//		}).
//		Exec(ctx)
func (_c *HostCreate) OnConflict(opts ...sql.ConflictOption) *HostUpsertOne {
	_c.conflict = opts
	return &HostUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Host.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HostCreate) OnConflictColumns(columns ...string) *HostUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HostUpsertOne{
		create: _c,
	}
}

type (
	// HostUpsertOne is the builder for "upsert"-ing
	//  one Host node.
	HostUpsertOne struct {
		create *HostCreate
	}

	// HostUpsert is the "OnConflict" setter.
	HostUpsert struct {
		*sql.UpdateSet
	}
)

// SetURL sets the "url" field.
func (u *HostUpsert) SetURL(v string) *HostUpsert {
	u.Set(host.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *HostUpsert) UpdateURL() *HostUpsert {
	u.SetExcluded(host.FieldURL)
	return u
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (u *HostUpsert) SetTokenEncrypted(v []byte) *HostUpsert {
	u.Set(host.FieldTokenEncrypted, v)
	return u
}

// UpdateTokenEncrypted sets the "token_encrypted" field to the value that was provided on create.
func (u *HostUpsert) UpdateTokenEncrypted() *HostUpsert {
	u.SetExcluded(host.FieldTokenEncrypted)
	return u
}

// ClearTokenEncrypted clears the value of the "token_encrypted" field.
func (u *HostUpsert) ClearTokenEncrypted() *HostUpsert {
	u.SetNull(host.FieldTokenEncrypted)
	return u
}

// SetRegion sets the "region" field.
func (u *HostUpsert) SetRegion(v string) *HostUpsert {
	u.Set(host.FieldRegion, v)
	return u
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *HostUpsert) UpdateRegion() *HostUpsert {
	u.SetExcluded(host.FieldRegion)
	return u
}

// SetState sets the "state" field.
func (u *HostUpsert) SetState(v host.State) *HostUpsert {
	u.Set(host.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *HostUpsert) UpdateState() *HostUpsert {
	u.SetExcluded(host.FieldState)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *HostUpsert) SetTenantID(v string) *HostUpsert {
	u.Set(host.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *HostUpsert) UpdateTenantID() *HostUpsert {
	u.SetExcluded(host.FieldTenantID)
	return u
}

// SetCpusTotal sets the "cpus_total" field.
func (u *HostUpsert) SetCpusTotal(v int) *HostUpsert {
	u.Set(host.FieldCpusTotal, v)
	return u
}

// UpdateCpusTotal sets the "cpus_total" field to the value that was provided on create.
func (u *HostUpsert) UpdateCpusTotal() *HostUpsert {
	u.SetExcluded(host.FieldCpusTotal)
	return u
}

// AddCpusTotal adds v to the "cpus_total" field.
func (u *HostUpsert) AddCpusTotal(v int) *HostUpsert {
	u.Add(host.FieldCpusTotal, v)
	return u
}

// SetRAMMBTotal sets the "ram_mb_total" field.
func (u *HostUpsert) SetRAMMBTotal(v int) *HostUpsert {
	u.Set(host.FieldRAMMBTotal, v)
	return u
}

// UpdateRAMMBTotal sets the "ram_mb_total" field to the value that was provided on create.
func (u *HostUpsert) UpdateRAMMBTotal() *HostUpsert {
	u.SetExcluded(host.FieldRAMMBTotal)
	return u
}

// AddRAMMBTotal adds v to the "ram_mb_total" field.
func (u *HostUpsert) AddRAMMBTotal(v int) *HostUpsert {
	u.Add(host.FieldRAMMBTotal, v)
	return u
}

// SetStorageGBTotal sets the "storage_gb_total" field.
func (u *HostUpsert) SetStorageGBTotal(v int) *HostUpsert {
	u.Set(host.FieldStorageGBTotal, v)
	return u
}

// UpdateStorageGBTotal sets the "storage_gb_total" field to the value that was provided on create.
func (u *HostUpsert) UpdateStorageGBTotal() *HostUpsert {
	u.SetExcluded(host.FieldStorageGBTotal)
	return u
}

// AddStorageGBTotal adds v to the "storage_gb_total" field.
func (u *HostUpsert) AddStorageGBTotal(v int) *HostUpsert {
	u.Add(host.FieldStorageGBTotal, v)
	return u
}

// SetVMCountMax sets the "vm_count_max" field.
func (u *HostUpsert) SetVMCountMax(v int) *HostUpsert {
	u.Set(host.FieldVMCountMax, v)
	return u
}

// UpdateVMCountMax sets the "vm_count_max" field to the value that was provided on create.
func (u *HostUpsert) UpdateVMCountMax() *HostUpsert {
	u.SetExcluded(host.FieldVMCountMax)
	return u
}

// AddVMCountMax adds v to the "vm_count_max" field.
func (u *HostUpsert) AddVMCountMax(v int) *HostUpsert {
	u.Add(host.FieldVMCountMax, v)
	return u
}

// SetCpusAllocated sets the "cpus_allocated" field.
func (u *HostUpsert) SetCpusAllocated(v int) *HostUpsert {
	u.Set(host.FieldCpusAllocated, v)
	return u
}

// UpdateCpusAllocated sets the "cpus_allocated" field to the value that was provided on create.
func (u *HostUpsert) UpdateCpusAllocated() *HostUpsert {
	u.SetExcluded(host.FieldCpusAllocated)
	return u
}

// AddCpusAllocated adds v to the "cpus_allocated" field.
func (u *HostUpsert) AddCpusAllocated(v int) *HostUpsert {
	u.Add(host.FieldCpusAllocated, v)
	return u
}

// SetRAMMBAllocated sets the "ram_mb_allocated" field.
func (u *HostUpsert) SetRAMMBAllocated(v int) *HostUpsert {
	u.Set(host.FieldRAMMBAllocated, v)
	return u
}

// UpdateRAMMBAllocated sets the "ram_mb_allocated" field to the value that was provided on create.
func (u *HostUpsert) UpdateRAMMBAllocated() *HostUpsert {
	u.SetExcluded(host.FieldRAMMBAllocated)
	return u
}

// AddRAMMBAllocated adds v to the "ram_mb_allocated" field.
func (u *HostUpsert) AddRAMMBAllocated(v int) *HostUpsert {
	u.Add(host.FieldRAMMBAllocated, v)
	return u
}

// SetStorageGBAllocated sets the "storage_gb_allocated" field.
func (u *HostUpsert) SetStorageGBAllocated(v int) *HostUpsert {
	u.Set(host.FieldStorageGBAllocated, v)
	return u
}

// UpdateStorageGBAllocated sets the "storage_gb_allocated" field to the value that was provided on create.
func (u *HostUpsert) UpdateStorageGBAllocated() *HostUpsert {
	u.SetExcluded(host.FieldStorageGBAllocated)
	return u
}

// AddStorageGBAllocated adds v to the "storage_gb_allocated" field.
func (u *HostUpsert) AddStorageGBAllocated(v int) *HostUpsert {
	u.Add(host.FieldStorageGBAllocated, v)
	return u
}

// SetVMCountAllocated sets the "vm_count_allocated" field.
func (u *HostUpsert) SetVMCountAllocated(v int) *HostUpsert {
	u.Set(host.FieldVMCountAllocated, v)
	return u
}

// UpdateVMCountAllocated sets the "vm_count_allocated" field to the value that was provided on create.
func (u *HostUpsert) UpdateVMCountAllocated() *HostUpsert {
	u.SetExcluded(host.FieldVMCountAllocated)
	return u
}

// AddVMCountAllocated adds v to the "vm_count_allocated" field.
func (u *HostUpsert) AddVMCountAllocated(v int) *HostUpsert {
	u.Add(host.FieldVMCountAllocated, v)
	return u
}

// SetLabels sets the "labels" field.
func (u *HostUpsert) SetLabels(v map[string]string) *HostUpsert {
	u.Set(host.FieldLabels, v)
	return u
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *HostUpsert) UpdateLabels() *HostUpsert {
	u.SetExcluded(host.FieldLabels)
	return u
}

// SetArch sets the "arch" field.
func (u *HostUpsert) SetArch(v string) *HostUpsert {
	u.Set(host.FieldArch, v)
	return u
}

// UpdateArch sets the "arch" field to the value that was provided on create.
func (u *HostUpsert) UpdateArch() *HostUpsert {
	u.SetExcluded(host.FieldArch)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *HostUpsert) SetLastSeenAt(v time.Time) *HostUpsert {
	u.Set(host.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *HostUpsert) UpdateLastSeenAt() *HostUpsert {
	u.SetExcluded(host.FieldLastSeenAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HostUpsert) SetUpdatedAt(v time.Time) *HostUpsert {
	u.Set(host.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HostUpsert) UpdateUpdatedAt() *HostUpsert {
	u.SetExcluded(host.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Host.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(host.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HostUpsertOne) UpdateNewValues() *HostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(host.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(host.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Host.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HostUpsertOne) Ignore() *HostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HostUpsertOne) DoNothing() *HostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HostCreate.OnConflict
// documentation for more info.
func (u *HostUpsertOne) Update(set func(*HostUpsert)) *HostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HostUpsert{UpdateSet: update})
	}))
	return u
}

// SetURL sets the "url" field.
func (u *HostUpsertOne) SetURL(v string) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateURL() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateURL()
	})
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (u *HostUpsertOne) SetTokenEncrypted(v []byte) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetTokenEncrypted(v)
	})
}

// UpdateTokenEncrypted sets the "token_encrypted" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateTokenEncrypted() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateTokenEncrypted()
	})
}

// ClearTokenEncrypted clears the value of the "token_encrypted" field.
func (u *HostUpsertOne) ClearTokenEncrypted() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.ClearTokenEncrypted()
	})
}

// SetRegion sets the "region" field.
func (u *HostUpsertOne) SetRegion(v string) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetRegion(v)
	})
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateRegion() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateRegion()
	})
}

// SetState sets the "state" field.
func (u *HostUpsertOne) SetState(v host.State) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateState() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateState()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *HostUpsertOne) SetTenantID(v string) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateTenantID() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateTenantID()
	})
}

// SetCpusTotal sets the "cpus_total" field.
func (u *HostUpsertOne) SetCpusTotal(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetCpusTotal(v)
	})
}

// AddCpusTotal adds v to the "cpus_total" field.
func (u *HostUpsertOne) AddCpusTotal(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.AddCpusTotal(v)
	})
}

// UpdateCpusTotal sets the "cpus_total" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateCpusTotal() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateCpusTotal()
	})
}

// SetRAMMBTotal sets the "ram_mb_total" field.
func (u *HostUpsertOne) SetRAMMBTotal(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetRAMMBTotal(v)
	})
}

// AddRAMMBTotal adds v to the "ram_mb_total" field.
func (u *HostUpsertOne) AddRAMMBTotal(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.AddRAMMBTotal(v)
	})
}

// UpdateRAMMBTotal sets the "ram_mb_total" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateRAMMBTotal() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateRAMMBTotal()
	})
}

// SetStorageGBTotal sets the "storage_gb_total" field.
func (u *HostUpsertOne) SetStorageGBTotal(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetStorageGBTotal(v)
	})
}

// AddStorageGBTotal adds v to the "storage_gb_total" field.
func (u *HostUpsertOne) AddStorageGBTotal(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.AddStorageGBTotal(v)
	})
}

// UpdateStorageGBTotal sets the "storage_gb_total" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateStorageGBTotal() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateStorageGBTotal()
	})
}

// SetVMCountMax sets the "vm_count_max" field.
func (u *HostUpsertOne) SetVMCountMax(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetVMCountMax(v)
	})
}

// AddVMCountMax adds v to the "vm_count_max" field.
func (u *HostUpsertOne) AddVMCountMax(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.AddVMCountMax(v)
	})
}

// UpdateVMCountMax sets the "vm_count_max" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateVMCountMax() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateVMCountMax()
	})
}

// SetCpusAllocated sets the "cpus_allocated" field.
func (u *HostUpsertOne) SetCpusAllocated(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetCpusAllocated(v)
	})
}

// AddCpusAllocated adds v to the "cpus_allocated" field.
func (u *HostUpsertOne) AddCpusAllocated(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.AddCpusAllocated(v)
	})
}

// UpdateCpusAllocated sets the "cpus_allocated" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateCpusAllocated() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateCpusAllocated()
	})
}

// SetRAMMBAllocated sets the "ram_mb_allocated" field.
func (u *HostUpsertOne) SetRAMMBAllocated(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetRAMMBAllocated(v)
	})
}

// AddRAMMBAllocated adds v to the "ram_mb_allocated" field.
func (u *HostUpsertOne) AddRAMMBAllocated(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.AddRAMMBAllocated(v)
	})
}

// UpdateRAMMBAllocated sets the "ram_mb_allocated" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateRAMMBAllocated() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateRAMMBAllocated()
	})
}

// SetStorageGBAllocated sets the "storage_gb_allocated" field.
func (u *HostUpsertOne) SetStorageGBAllocated(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetStorageGBAllocated(v)
	})
}

// AddStorageGBAllocated adds v to the "storage_gb_allocated" field.
func (u *HostUpsertOne) AddStorageGBAllocated(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.AddStorageGBAllocated(v)
	})
}

// UpdateStorageGBAllocated sets the "storage_gb_allocated" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateStorageGBAllocated() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateStorageGBAllocated()
	})
}

// SetVMCountAllocated sets the "vm_count_allocated" field.
func (u *HostUpsertOne) SetVMCountAllocated(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetVMCountAllocated(v)
	})
}

// AddVMCountAllocated adds v to the "vm_count_allocated" field.
func (u *HostUpsertOne) AddVMCountAllocated(v int) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.AddVMCountAllocated(v)
	})
}

// UpdateVMCountAllocated sets the "vm_count_allocated" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateVMCountAllocated() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateVMCountAllocated()
	})
}

// SetLabels sets the "labels" field.
func (u *HostUpsertOne) SetLabels(v map[string]string) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateLabels() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateLabels()
	})
}

// SetArch sets the "arch" field.
func (u *HostUpsertOne) SetArch(v string) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetArch(v)
	})
}

// UpdateArch sets the "arch" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateArch() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateArch()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *HostUpsertOne) SetLastSeenAt(v time.Time) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateLastSeenAt() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HostUpsertOne) SetUpdatedAt(v time.Time) *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HostUpsertOne) UpdateUpdatedAt() *HostUpsertOne {
	return u.Update(func(s *HostUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *HostUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HostCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HostUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HostUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: HostUpsertOne.ID is not supported by MySQL driver. Use HostUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HostUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HostCreateBulk is the builder for creating many Host entities in bulk.
type HostCreateBulk struct {
	config
	err      error
	builders []*HostCreate
	conflict []sql.ConflictOption
}

// Save creates the Host entities in the database.
func (_c *HostCreateBulk) Save(ctx context.Context) ([]*Host, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Host, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HostCreateBulk) SaveX(ctx context.Context) []*Host {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Host.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HostUpsert) {
//			SetURL(v+v).
//		}).
//		Exec(ctx)
func (_c *HostCreateBulk) OnConflict(opts ...sql.ConflictOption) *HostUpsertBulk {
	_c.conflict = opts
	return &HostUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Host.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HostCreateBulk) OnConflictColumns(columns ...string) *HostUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HostUpsertBulk{
		create: _c,
	}
}

// HostUpsertBulk is the builder for "upsert"-ing
// a bulk of Host nodes.
type HostUpsertBulk struct {
	create *HostCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Host.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(host.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HostUpsertBulk) UpdateNewValues() *HostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(host.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(host.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Host.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HostUpsertBulk) Ignore() *HostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HostUpsertBulk) DoNothing() *HostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HostCreateBulk.OnConflict
// documentation for more info.
func (u *HostUpsertBulk) Update(set func(*HostUpsert)) *HostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HostUpsert{UpdateSet: update})
	}))
	return u
}

// SetURL sets the "url" field.
func (u *HostUpsertBulk) SetURL(v string) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateURL() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateURL()
	})
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (u *HostUpsertBulk) SetTokenEncrypted(v []byte) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetTokenEncrypted(v)
	})
}

// UpdateTokenEncrypted sets the "token_encrypted" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateTokenEncrypted() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateTokenEncrypted()
	})
}

// ClearTokenEncrypted clears the value of the "token_encrypted" field.
func (u *HostUpsertBulk) ClearTokenEncrypted() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.ClearTokenEncrypted()
	})
}

// SetRegion sets the "region" field.
func (u *HostUpsertBulk) SetRegion(v string) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetRegion(v)
	})
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateRegion() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateRegion()
	})
}

// SetState sets the "state" field.
func (u *HostUpsertBulk) SetState(v host.State) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateState() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateState()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *HostUpsertBulk) SetTenantID(v string) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateTenantID() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateTenantID()
	})
}

// SetCpusTotal sets the "cpus_total" field.
func (u *HostUpsertBulk) SetCpusTotal(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetCpusTotal(v)
	})
}

// AddCpusTotal adds v to the "cpus_total" field.
func (u *HostUpsertBulk) AddCpusTotal(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.AddCpusTotal(v)
	})
}

// UpdateCpusTotal sets the "cpus_total" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateCpusTotal() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateCpusTotal()
	})
}

// SetRAMMBTotal sets the "ram_mb_total" field.
func (u *HostUpsertBulk) SetRAMMBTotal(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetRAMMBTotal(v)
	})
}

// AddRAMMBTotal adds v to the "ram_mb_total" field.
func (u *HostUpsertBulk) AddRAMMBTotal(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.AddRAMMBTotal(v)
	})
}

// UpdateRAMMBTotal sets the "ram_mb_total" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateRAMMBTotal() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateRAMMBTotal()
	})
}

// SetStorageGBTotal sets the "storage_gb_total" field.
func (u *HostUpsertBulk) SetStorageGBTotal(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetStorageGBTotal(v)
	})
}

// AddStorageGBTotal adds v to the "storage_gb_total" field.
func (u *HostUpsertBulk) AddStorageGBTotal(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.AddStorageGBTotal(v)
	})
}

// UpdateStorageGBTotal sets the "storage_gb_total" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateStorageGBTotal() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateStorageGBTotal()
	})
}

// SetVMCountMax sets the "vm_count_max" field.
func (u *HostUpsertBulk) SetVMCountMax(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetVMCountMax(v)
	})
}

// AddVMCountMax adds v to the "vm_count_max" field.
func (u *HostUpsertBulk) AddVMCountMax(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.AddVMCountMax(v)
	})
}

// UpdateVMCountMax sets the "vm_count_max" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateVMCountMax() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateVMCountMax()
	})
}

// SetCpusAllocated sets the "cpus_allocated" field.
func (u *HostUpsertBulk) SetCpusAllocated(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetCpusAllocated(v)
	})
}

// AddCpusAllocated adds v to the "cpus_allocated" field.
func (u *HostUpsertBulk) AddCpusAllocated(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.AddCpusAllocated(v)
	})
}

// UpdateCpusAllocated sets the "cpus_allocated" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateCpusAllocated() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateCpusAllocated()
	})
}

// SetRAMMBAllocated sets the "ram_mb_allocated" field.
func (u *HostUpsertBulk) SetRAMMBAllocated(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetRAMMBAllocated(v)
	})
}

// AddRAMMBAllocated adds v to the "ram_mb_allocated" field.
func (u *HostUpsertBulk) AddRAMMBAllocated(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.AddRAMMBAllocated(v)
	})
}

// UpdateRAMMBAllocated sets the "ram_mb_allocated" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateRAMMBAllocated() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateRAMMBAllocated()
	})
}

// SetStorageGBAllocated sets the "storage_gb_allocated" field.
func (u *HostUpsertBulk) SetStorageGBAllocated(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetStorageGBAllocated(v)
	})
}

// AddStorageGBAllocated adds v to the "storage_gb_allocated" field.
func (u *HostUpsertBulk) AddStorageGBAllocated(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.AddStorageGBAllocated(v)
	})
}

// UpdateStorageGBAllocated sets the "storage_gb_allocated" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateStorageGBAllocated() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateStorageGBAllocated()
	})
}

// SetVMCountAllocated sets the "vm_count_allocated" field.
func (u *HostUpsertBulk) SetVMCountAllocated(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetVMCountAllocated(v)
	})
}

// AddVMCountAllocated adds v to the "vm_count_allocated" field.
func (u *HostUpsertBulk) AddVMCountAllocated(v int) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.AddVMCountAllocated(v)
	})
}

// UpdateVMCountAllocated sets the "vm_count_allocated" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateVMCountAllocated() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateVMCountAllocated()
	})
}

// SetLabels sets the "labels" field.
func (u *HostUpsertBulk) SetLabels(v map[string]string) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateLabels() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateLabels()
	})
}

// SetArch sets the "arch" field.
func (u *HostUpsertBulk) SetArch(v string) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetArch(v)
	})
}

// UpdateArch sets the "arch" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateArch() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateArch()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *HostUpsertBulk) SetLastSeenAt(v time.Time) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateLastSeenAt() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HostUpsertBulk) SetUpdatedAt(v time.Time) *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HostUpsertBulk) UpdateUpdatedAt() *HostUpsertBulk {
	return u.Update(func(s *HostUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *HostUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HostCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HostCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HostUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
