// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/folsomintel/fuse/internal/entspike/ent/host"
)

// Host is the model entity for the Host schema.
type Host struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// TokenEncrypted holds the value of the "token_encrypted" field.
	TokenEncrypted []byte `json:"token_encrypted,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// State holds the value of the "state" field.
	State host.State `json:"state,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// CpusTotal holds the value of the "cpus_total" field.
	CpusTotal int `json:"cpus_total,omitempty"`
	// RAMMBTotal holds the value of the "ram_mb_total" field.
	RAMMBTotal int `json:"ram_mb_total,omitempty"`
	// StorageGBTotal holds the value of the "storage_gb_total" field.
	StorageGBTotal int `json:"storage_gb_total,omitempty"`
	// VMCountMax holds the value of the "vm_count_max" field.
	VMCountMax int `json:"vm_count_max,omitempty"`
	// CpusAllocated holds the value of the "cpus_allocated" field.
	CpusAllocated int `json:"cpus_allocated,omitempty"`
	// RAMMBAllocated holds the value of the "ram_mb_allocated" field.
	RAMMBAllocated int `json:"ram_mb_allocated,omitempty"`
	// StorageGBAllocated holds the value of the "storage_gb_allocated" field.
	StorageGBAllocated int `json:"storage_gb_allocated,omitempty"`
	// VMCountAllocated holds the value of the "vm_count_allocated" field.
	VMCountAllocated int `json:"vm_count_allocated,omitempty"`
	// Labels holds the value of the "labels" field.
	Labels map[string]string `json:"labels,omitempty"`
	// Arch holds the value of the "arch" field.
	Arch string `json:"arch,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Host) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case host.FieldTokenEncrypted, host.FieldLabels:
			values[i] = new([]byte)
		case host.FieldCpusTotal, host.FieldRAMMBTotal, host.FieldStorageGBTotal, host.FieldVMCountMax, host.FieldCpusAllocated, host.FieldRAMMBAllocated, host.FieldStorageGBAllocated, host.FieldVMCountAllocated:
			values[i] = new(sql.NullInt64)
		case host.FieldID, host.FieldURL, host.FieldRegion, host.FieldState, host.FieldTenantID, host.FieldArch:
			values[i] = new(sql.NullString)
		case host.FieldLastSeenAt, host.FieldCreatedAt, host.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Host fields.
func (_m *Host) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case host.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case host.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case host.FieldTokenEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field token_encrypted", values[i])
			} else if value != nil {
				_m.TokenEncrypted = *value
			}
		case host.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case host.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = host.State(value.String)
			}
		case host.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case host.FieldCpusTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cpus_total", values[i])
			} else if value.Valid {
				_m.CpusTotal = int(value.Int64)
			}
		case host.FieldRAMMBTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ram_mb_total", values[i])
			} else if value.Valid {
				_m.RAMMBTotal = int(value.Int64)
			}
		case host.FieldStorageGBTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field storage_gb_total", values[i])
			} else if value.Valid {
				_m.StorageGBTotal = int(value.Int64)
			}
		case host.FieldVMCountMax:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vm_count_max", values[i])
			} else if value.Valid {
				_m.VMCountMax = int(value.Int64)
			}
		case host.FieldCpusAllocated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cpus_allocated", values[i])
			} else if value.Valid {
				_m.CpusAllocated = int(value.Int64)
			}
		case host.FieldRAMMBAllocated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ram_mb_allocated", values[i])
			} else if value.Valid {
				_m.RAMMBAllocated = int(value.Int64)
			}
		case host.FieldStorageGBAllocated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field storage_gb_allocated", values[i])
			} else if value.Valid {
				_m.StorageGBAllocated = int(value.Int64)
			}
		case host.FieldVMCountAllocated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vm_count_allocated", values[i])
			} else if value.Valid {
				_m.VMCountAllocated = int(value.Int64)
			}
		case host.FieldLabels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field labels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Labels); err != nil {
					return fmt.Errorf("unmarshal field labels: %w", err)
				}
			}
		case host.FieldArch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field arch", values[i])
			} else if value.Valid {
				_m.Arch = value.String
			}
		case host.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case host.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case host.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Host.
// This includes values selected through modifiers, order, etc.
func (_m *Host) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Host.
// Note that you need to call Host.Unwrap() before calling this method if this Host
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Host) Update() *HostUpdateOne {
	return NewHostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Host entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Host) Unwrap() *Host {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Host is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Host) String() string {
	var builder strings.Builder
	builder.WriteString("Host(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("token_encrypted=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenEncrypted))
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("cpus_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.CpusTotal))
	builder.WriteString(", ")
	builder.WriteString("ram_mb_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.RAMMBTotal))
	builder.WriteString(", ")
	builder.WriteString("storage_gb_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.StorageGBTotal))
	builder.WriteString(", ")
	builder.WriteString("vm_count_max=")
	builder.WriteString(fmt.Sprintf("%v", _m.VMCountMax))
	builder.WriteString(", ")
	builder.WriteString("cpus_allocated=")
	builder.WriteString(fmt.Sprintf("%v", _m.CpusAllocated))
	builder.WriteString(", ")
	builder.WriteString("ram_mb_allocated=")
	builder.WriteString(fmt.Sprintf("%v", _m.RAMMBAllocated))
	builder.WriteString(", ")
	builder.WriteString("storage_gb_allocated=")
	builder.WriteString(fmt.Sprintf("%v", _m.StorageGBAllocated))
	builder.WriteString(", ")
	builder.WriteString("vm_count_allocated=")
	builder.WriteString(fmt.Sprintf("%v", _m.VMCountAllocated))
	builder.WriteString(", ")
	builder.WriteString("labels=")
	builder.WriteString(fmt.Sprintf("%v", _m.Labels))
	builder.WriteString(", ")
	builder.WriteString("arch=")
	builder.WriteString(_m.Arch)
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Hosts is a parsable slice of Host.
type Hosts []*Host
