// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/folsomintel/fuse/internal/entspike/ent/host"
	"github.com/folsomintel/fuse/internal/entspike/ent/schema"
	"github.com/folsomintel/fuse/internal/entspike/ent/vm"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hostFields := schema.Host{}.Fields()
	_ = hostFields
	// hostDescRegion is the schema descriptor for region field.
	hostDescRegion := hostFields[3].Descriptor()
	// host.DefaultRegion holds the default value on creation for the region field.
	host.DefaultRegion = hostDescRegion.Default.(string)
	// hostDescTenantID is the schema descriptor for tenant_id field.
	hostDescTenantID := hostFields[5].Descriptor()
	// host.DefaultTenantID holds the default value on creation for the tenant_id field.
	host.DefaultTenantID = hostDescTenantID.Default.(string)
	// hostDescCpusTotal is the schema descriptor for cpus_total field.
	hostDescCpusTotal := hostFields[6].Descriptor()
	// host.DefaultCpusTotal holds the default value on creation for the cpus_total field.
	host.DefaultCpusTotal = hostDescCpusTotal.Default.(int)
	// hostDescRAMMBTotal is the schema descriptor for ram_mb_total field.
	hostDescRAMMBTotal := hostFields[7].Descriptor()
	// host.DefaultRAMMBTotal holds the default value on creation for the ram_mb_total field.
	host.DefaultRAMMBTotal = hostDescRAMMBTotal.Default.(int)
	// hostDescStorageGBTotal is the schema descriptor for storage_gb_total field.
	hostDescStorageGBTotal := hostFields[8].Descriptor()
	// host.DefaultStorageGBTotal holds the default value on creation for the storage_gb_total field.
	host.DefaultStorageGBTotal = hostDescStorageGBTotal.Default.(int)
	// hostDescVMCountMax is the schema descriptor for vm_count_max field.
	hostDescVMCountMax := hostFields[9].Descriptor()
	// host.DefaultVMCountMax holds the default value on creation for the vm_count_max field.
	host.DefaultVMCountMax = hostDescVMCountMax.Default.(int)
	// hostDescCpusAllocated is the schema descriptor for cpus_allocated field.
	hostDescCpusAllocated := hostFields[10].Descriptor()
	// host.DefaultCpusAllocated holds the default value on creation for the cpus_allocated field.
	host.DefaultCpusAllocated = hostDescCpusAllocated.Default.(int)
	// hostDescRAMMBAllocated is the schema descriptor for ram_mb_allocated field.
	hostDescRAMMBAllocated := hostFields[11].Descriptor()
	// host.DefaultRAMMBAllocated holds the default value on creation for the ram_mb_allocated field.
	host.DefaultRAMMBAllocated = hostDescRAMMBAllocated.Default.(int)
	// hostDescStorageGBAllocated is the schema descriptor for storage_gb_allocated field.
	hostDescStorageGBAllocated := hostFields[12].Descriptor()
	// host.DefaultStorageGBAllocated holds the default value on creation for the storage_gb_allocated field.
	host.DefaultStorageGBAllocated = hostDescStorageGBAllocated.Default.(int)
	// hostDescVMCountAllocated is the schema descriptor for vm_count_allocated field.
	hostDescVMCountAllocated := hostFields[13].Descriptor()
	// host.DefaultVMCountAllocated holds the default value on creation for the vm_count_allocated field.
	host.DefaultVMCountAllocated = hostDescVMCountAllocated.Default.(int)
	// hostDescLabels is the schema descriptor for labels field.
	hostDescLabels := hostFields[14].Descriptor()
	// host.DefaultLabels holds the default value on creation for the labels field.
	host.DefaultLabels = hostDescLabels.Default.(map[string]string)
	// hostDescArch is the schema descriptor for arch field.
	hostDescArch := hostFields[15].Descriptor()
	// host.DefaultArch holds the default value on creation for the arch field.
	host.DefaultArch = hostDescArch.Default.(string)
	// hostDescCreatedAt is the schema descriptor for created_at field.
	hostDescCreatedAt := hostFields[17].Descriptor()
	// host.DefaultCreatedAt holds the default value on creation for the created_at field.
	host.DefaultCreatedAt = hostDescCreatedAt.Default.(func() time.Time)
	// hostDescUpdatedAt is the schema descriptor for updated_at field.
	hostDescUpdatedAt := hostFields[18].Descriptor()
	// host.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	host.DefaultUpdatedAt = hostDescUpdatedAt.Default.(func() time.Time)
	// host.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	host.UpdateDefaultUpdatedAt = hostDescUpdatedAt.UpdateDefault.(func() time.Time)
	vmFields := schema.VM{}.Fields()
	_ = vmFields
	// vmDescHostID is the schema descriptor for host_id field.
	vmDescHostID := vmFields[1].Descriptor()
	// vm.DefaultHostID holds the default value on creation for the host_id field.
	vm.DefaultHostID = vmDescHostID.Default.(string)
	// vmDescNetworkHost is the schema descriptor for network_host field.
	vmDescNetworkHost := vmFields[2].Descriptor()
	// vm.DefaultNetworkHost holds the default value on creation for the network_host field.
	vm.DefaultNetworkHost = vmDescNetworkHost.Default.(string)
	// vmDescURL is the schema descriptor for url field.
	vmDescURL := vmFields[4].Descriptor()
	// vm.DefaultURL holds the default value on creation for the url field.
	vm.DefaultURL = vmDescURL.Default.(string)
	// vmDescTaskID is the schema descriptor for task_id field.
	vmDescTaskID := vmFields[5].Descriptor()
	// vm.DefaultTaskID holds the default value on creation for the task_id field.
	vm.DefaultTaskID = vmDescTaskID.Default.(string)
	// vmDescTenantID is the schema descriptor for tenant_id field.
	vmDescTenantID := vmFields[6].Descriptor()
	// vm.DefaultTenantID holds the default value on creation for the tenant_id field.
	vm.DefaultTenantID = vmDescTenantID.Default.(string)
	// vmDescCpus is the schema descriptor for cpus field.
	vmDescCpus := vmFields[7].Descriptor()
	// vm.DefaultCpus holds the default value on creation for the cpus field.
	vm.DefaultCpus = vmDescCpus.Default.(int)
	// vmDescRAMMB is the schema descriptor for ram_mb field.
	vmDescRAMMB := vmFields[8].Descriptor()
	// vm.DefaultRAMMB holds the default value on creation for the ram_mb field.
	vm.DefaultRAMMB = vmDescRAMMB.Default.(int)
	// vmDescStorageGB is the schema descriptor for storage_gb field.
	vmDescStorageGB := vmFields[9].Descriptor()
	// vm.DefaultStorageGB holds the default value on creation for the storage_gb field.
	vm.DefaultStorageGB = vmDescStorageGB.Default.(int)
	// vmDescRegion is the schema descriptor for region field.
	vmDescRegion := vmFields[10].Descriptor()
	// vm.DefaultRegion holds the default value on creation for the region field.
	vm.DefaultRegion = vmDescRegion.Default.(string)
	// vmDescMaxRuntimeSeconds is the schema descriptor for max_runtime_seconds field.
	vmDescMaxRuntimeSeconds := vmFields[11].Descriptor()
	// vm.DefaultMaxRuntimeSeconds holds the default value on creation for the max_runtime_seconds field.
	vm.DefaultMaxRuntimeSeconds = vmDescMaxRuntimeSeconds.Default.(int)
	// vmDescIdleTimeoutSeconds is the schema descriptor for idle_timeout_seconds field.
	vmDescIdleTimeoutSeconds := vmFields[12].Descriptor()
	// vm.DefaultIdleTimeoutSeconds holds the default value on creation for the idle_timeout_seconds field.
	vm.DefaultIdleTimeoutSeconds = vmDescIdleTimeoutSeconds.Default.(int)
	// vmDescLastError is the schema descriptor for last_error field.
	vmDescLastError := vmFields[15].Descriptor()
	// vm.DefaultLastError holds the default value on creation for the last_error field.
	vm.DefaultLastError = vmDescLastError.Default.(string)
	// vmDescGpus is the schema descriptor for gpus field.
	vmDescGpus := vmFields[17].Descriptor()
	// vm.DefaultGpus holds the default value on creation for the gpus field.
	vm.DefaultGpus = vmDescGpus.Default.(int32)
	// vmDescGpuKind is the schema descriptor for gpu_kind field.
	vmDescGpuKind := vmFields[18].Descriptor()
	// vm.DefaultGpuKind holds the default value on creation for the gpu_kind field.
	vm.DefaultGpuKind = vmDescGpuKind.Default.(string)
	// vmDescGpuProfile is the schema descriptor for gpu_profile field.
	vmDescGpuProfile := vmFields[19].Descriptor()
	// vm.DefaultGpuProfile holds the default value on creation for the gpu_profile field.
	vm.DefaultGpuProfile = vmDescGpuProfile.Default.(string)
}
