// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/folsomintel/fuse/internal/entspike/ent/vm"
)

// VM is the model entity for the VM schema.
type VM struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// HostID holds the value of the "host_id" field.
	HostID string `json:"host_id,omitempty"`
	// NetworkHost holds the value of the "network_host" field.
	NetworkHost string `json:"network_host,omitempty"`
	// State holds the value of the "state" field.
	State vm.State `json:"state,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Cpus holds the value of the "cpus" field.
	Cpus int `json:"cpus,omitempty"`
	// RAMMB holds the value of the "ram_mb" field.
	RAMMB int `json:"ram_mb,omitempty"`
	// StorageGB holds the value of the "storage_gb" field.
	StorageGB int `json:"storage_gb,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// MaxRuntimeSeconds holds the value of the "max_runtime_seconds" field.
	MaxRuntimeSeconds int `json:"max_runtime_seconds,omitempty"`
	// IdleTimeoutSeconds holds the value of the "idle_timeout_seconds" field.
	IdleTimeoutSeconds int `json:"idle_timeout_seconds,omitempty"`
	// AuthTokenEncrypted holds the value of the "auth_token_encrypted" field.
	AuthTokenEncrypted []byte `json:"auth_token_encrypted,omitempty"`
	// SecretsEncrypted holds the value of the "secrets_encrypted" field.
	SecretsEncrypted []byte `json:"secrets_encrypted,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// Endpoints holds the value of the "endpoints" field.
	Endpoints json.RawMessage `json:"endpoints,omitempty"`
	// Gpus holds the value of the "gpus" field.
	Gpus int32 `json:"gpus,omitempty"`
	// GpuKind holds the value of the "gpu_kind" field.
	GpuKind string `json:"gpu_kind,omitempty"`
	// GpuProfile holds the value of the "gpu_profile" field.
	GpuProfile string `json:"gpu_profile,omitempty"`
	// GpuUuids holds the value of the "gpu_uuids" field.
	GpuUuids json.RawMessage `json:"gpu_uuids,omitempty"`
	// MigInstanceUuids holds the value of the "mig_instance_uuids" field.
	MigInstanceUuids json.RawMessage `json:"mig_instance_uuids,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VM) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vm.FieldAuthTokenEncrypted, vm.FieldSecretsEncrypted, vm.FieldEndpoints, vm.FieldGpuUuids, vm.FieldMigInstanceUuids:
			values[i] = new([]byte)
		case vm.FieldCpus, vm.FieldRAMMB, vm.FieldStorageGB, vm.FieldMaxRuntimeSeconds, vm.FieldIdleTimeoutSeconds, vm.FieldGpus:
			values[i] = new(sql.NullInt64)
		case vm.FieldID, vm.FieldHostID, vm.FieldNetworkHost, vm.FieldState, vm.FieldURL, vm.FieldTaskID, vm.FieldTenantID, vm.FieldRegion, vm.FieldLastError, vm.FieldGpuKind, vm.FieldGpuProfile:
			values[i] = new(sql.NullString)
		case vm.FieldCreatedAt, vm.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VM fields.
func (_m *VM) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vm.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case vm.FieldHostID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host_id", values[i])
			} else if value.Valid {
				_m.HostID = value.String
			}
		case vm.FieldNetworkHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network_host", values[i])
			} else if value.Valid {
				_m.NetworkHost = value.String
			}
		case vm.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = vm.State(value.String)
			}
		case vm.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case vm.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case vm.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case vm.FieldCpus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cpus", values[i])
			} else if value.Valid {
				_m.Cpus = int(value.Int64)
			}
		case vm.FieldRAMMB:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ram_mb", values[i])
			} else if value.Valid {
				_m.RAMMB = int(value.Int64)
			}
		case vm.FieldStorageGB:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field storage_gb", values[i])
			} else if value.Valid {
				_m.StorageGB = int(value.Int64)
			}
		case vm.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case vm.FieldMaxRuntimeSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_runtime_seconds", values[i])
			} else if value.Valid {
				_m.MaxRuntimeSeconds = int(value.Int64)
			}
		case vm.FieldIdleTimeoutSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field idle_timeout_seconds", values[i])
			} else if value.Valid {
				_m.IdleTimeoutSeconds = int(value.Int64)
			}
		case vm.FieldAuthTokenEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field auth_token_encrypted", values[i])
			} else if value != nil {
				_m.AuthTokenEncrypted = *value
			}
		case vm.FieldSecretsEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secrets_encrypted", values[i])
			} else if value != nil {
				_m.SecretsEncrypted = *value
			}
		case vm.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case vm.FieldEndpoints:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field endpoints", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Endpoints); err != nil {
					return fmt.Errorf("unmarshal field endpoints: %w", err)
				}
			}
		case vm.FieldGpus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gpus", values[i])
			} else if value.Valid {
				_m.Gpus = int32(value.Int64)
			}
		case vm.FieldGpuKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gpu_kind", values[i])
			} else if value.Valid {
				_m.GpuKind = value.String
			}
		case vm.FieldGpuProfile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gpu_profile", values[i])
			} else if value.Valid {
				_m.GpuProfile = value.String
			}
		case vm.FieldGpuUuids:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field gpu_uuids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GpuUuids); err != nil {
					return fmt.Errorf("unmarshal field gpu_uuids: %w", err)
				}
			}
		case vm.FieldMigInstanceUuids:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field mig_instance_uuids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MigInstanceUuids); err != nil {
					return fmt.Errorf("unmarshal field mig_instance_uuids: %w", err)
				}
			}
		case vm.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case vm.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VM.
// This includes values selected through modifiers, order, etc.
func (_m *VM) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VM.
// Note that you need to call VM.Unwrap() before calling this method if this VM
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VM) Update() *VMUpdateOne {
	return NewVMClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VM entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VM) Unwrap() *VM {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VM is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VM) String() string {
	var builder strings.Builder
	builder.WriteString("VM(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("host_id=")
	builder.WriteString(_m.HostID)
	builder.WriteString(", ")
	builder.WriteString("network_host=")
	builder.WriteString(_m.NetworkHost)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("cpus=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cpus))
	builder.WriteString(", ")
	builder.WriteString("ram_mb=")
	builder.WriteString(fmt.Sprintf("%v", _m.RAMMB))
	builder.WriteString(", ")
	builder.WriteString("storage_gb=")
	builder.WriteString(fmt.Sprintf("%v", _m.StorageGB))
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("max_runtime_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxRuntimeSeconds))
	builder.WriteString(", ")
	builder.WriteString("idle_timeout_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.IdleTimeoutSeconds))
	builder.WriteString(", ")
	builder.WriteString("auth_token_encrypted=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthTokenEncrypted))
	builder.WriteString(", ")
	builder.WriteString("secrets_encrypted=")
	builder.WriteString(fmt.Sprintf("%v", _m.SecretsEncrypted))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("endpoints=")
	builder.WriteString(fmt.Sprintf("%v", _m.Endpoints))
	builder.WriteString(", ")
	builder.WriteString("gpus=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gpus))
	builder.WriteString(", ")
	builder.WriteString("gpu_kind=")
	builder.WriteString(_m.GpuKind)
	builder.WriteString(", ")
	builder.WriteString("gpu_profile=")
	builder.WriteString(_m.GpuProfile)
	builder.WriteString(", ")
	builder.WriteString("gpu_uuids=")
	builder.WriteString(fmt.Sprintf("%v", _m.GpuUuids))
	builder.WriteString(", ")
	builder.WriteString("mig_instance_uuids=")
	builder.WriteString(fmt.Sprintf("%v", _m.MigInstanceUuids))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VMs is a parsable slice of VM.
type VMs []*VM
