// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/folsomintel/fuse/internal/entspike/ent/predicate"
	"github.com/folsomintel/fuse/internal/entspike/ent/vm"
)

// VMUpdate is the builder for updating VM entities.
type VMUpdate struct {
	config
	hooks    []Hook
	mutation *VMMutation
}

// Where appends a list predicates to the VMUpdate builder.
func (_u *VMUpdate) Where(ps ...predicate.VM) *VMUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHostID sets the "host_id" field.
func (_u *VMUpdate) SetHostID(v string) *VMUpdate {
	_u.mutation.SetHostID(v)
	return _u
}

// SetNillableHostID sets the "host_id" field if the given value is not nil.
func (_u *VMUpdate) SetNillableHostID(v *string) *VMUpdate {
	if v != nil {
		_u.SetHostID(*v)
	}
	return _u
}

// SetNetworkHost sets the "network_host" field.
func (_u *VMUpdate) SetNetworkHost(v string) *VMUpdate {
	_u.mutation.SetNetworkHost(v)
	return _u
}

// SetNillableNetworkHost sets the "network_host" field if the given value is not nil.
func (_u *VMUpdate) SetNillableNetworkHost(v *string) *VMUpdate {
	if v != nil {
		_u.SetNetworkHost(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *VMUpdate) SetState(v vm.State) *VMUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *VMUpdate) SetNillableState(v *vm.State) *VMUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *VMUpdate) SetURL(v string) *VMUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *VMUpdate) SetNillableURL(v *string) *VMUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *VMUpdate) SetTaskID(v string) *VMUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *VMUpdate) SetNillableTaskID(v *string) *VMUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *VMUpdate) SetTenantID(v string) *VMUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *VMUpdate) SetNillableTenantID(v *string) *VMUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCpus sets the "cpus" field.
func (_u *VMUpdate) SetCpus(v int) *VMUpdate {
	_u.mutation.ResetCpus()
	_u.mutation.SetCpus(v)
	return _u
}

// SetNillableCpus sets the "cpus" field if the given value is not nil.
func (_u *VMUpdate) SetNillableCpus(v *int) *VMUpdate {
	if v != nil {
		_u.SetCpus(*v)
	}
	return _u
}

// AddCpus adds value to the "cpus" field.
func (_u *VMUpdate) AddCpus(v int) *VMUpdate {
	_u.mutation.AddCpus(v)
	return _u
}

// SetRAMMB sets the "ram_mb" field.
func (_u *VMUpdate) SetRAMMB(v int) *VMUpdate {
	_u.mutation.ResetRAMMB()
	_u.mutation.SetRAMMB(v)
	return _u
}

// SetNillableRAMMB sets the "ram_mb" field if the given value is not nil.
func (_u *VMUpdate) SetNillableRAMMB(v *int) *VMUpdate {
	if v != nil {
		_u.SetRAMMB(*v)
	}
	return _u
}

// AddRAMMB adds value to the "ram_mb" field.
func (_u *VMUpdate) AddRAMMB(v int) *VMUpdate {
	_u.mutation.AddRAMMB(v)
	return _u
}

// SetStorageGB sets the "storage_gb" field.
func (_u *VMUpdate) SetStorageGB(v int) *VMUpdate {
	_u.mutation.ResetStorageGB()
	_u.mutation.SetStorageGB(v)
	return _u
}

// SetNillableStorageGB sets the "storage_gb" field if the given value is not nil.
func (_u *VMUpdate) SetNillableStorageGB(v *int) *VMUpdate {
	if v != nil {
		_u.SetStorageGB(*v)
	}
	return _u
}

// AddStorageGB adds value to the "storage_gb" field.
func (_u *VMUpdate) AddStorageGB(v int) *VMUpdate {
	_u.mutation.AddStorageGB(v)
	return _u
}

// SetRegion sets the "region" field.
func (_u *VMUpdate) SetRegion(v string) *VMUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *VMUpdate) SetNillableRegion(v *string) *VMUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetMaxRuntimeSeconds sets the "max_runtime_seconds" field.
func (_u *VMUpdate) SetMaxRuntimeSeconds(v int) *VMUpdate {
	_u.mutation.ResetMaxRuntimeSeconds()
	_u.mutation.SetMaxRuntimeSeconds(v)
	return _u
}

// SetNillableMaxRuntimeSeconds sets the "max_runtime_seconds" field if the given value is not nil.
func (_u *VMUpdate) SetNillableMaxRuntimeSeconds(v *int) *VMUpdate {
	if v != nil {
		_u.SetMaxRuntimeSeconds(*v)
	}
	return _u
}

// AddMaxRuntimeSeconds adds value to the "max_runtime_seconds" field.
func (_u *VMUpdate) AddMaxRuntimeSeconds(v int) *VMUpdate {
	_u.mutation.AddMaxRuntimeSeconds(v)
	return _u
}

// SetIdleTimeoutSeconds sets the "idle_timeout_seconds" field.
func (_u *VMUpdate) SetIdleTimeoutSeconds(v int) *VMUpdate {
	_u.mutation.ResetIdleTimeoutSeconds()
	_u.mutation.SetIdleTimeoutSeconds(v)
	return _u
}

// SetNillableIdleTimeoutSeconds sets the "idle_timeout_seconds" field if the given value is not nil.
func (_u *VMUpdate) SetNillableIdleTimeoutSeconds(v *int) *VMUpdate {
	if v != nil {
		_u.SetIdleTimeoutSeconds(*v)
	}
	return _u
}

// AddIdleTimeoutSeconds adds value to the "idle_timeout_seconds" field.
func (_u *VMUpdate) AddIdleTimeoutSeconds(v int) *VMUpdate {
	_u.mutation.AddIdleTimeoutSeconds(v)
	return _u
}

// SetAuthTokenEncrypted sets the "auth_token_encrypted" field.
func (_u *VMUpdate) SetAuthTokenEncrypted(v []byte) *VMUpdate {
	_u.mutation.SetAuthTokenEncrypted(v)
	return _u
}

// ClearAuthTokenEncrypted clears the value of the "auth_token_encrypted" field.
func (_u *VMUpdate) ClearAuthTokenEncrypted() *VMUpdate {
	_u.mutation.ClearAuthTokenEncrypted()
	return _u
}

// SetSecretsEncrypted sets the "secrets_encrypted" field.
func (_u *VMUpdate) SetSecretsEncrypted(v []byte) *VMUpdate {
	_u.mutation.SetSecretsEncrypted(v)
	return _u
}

// ClearSecretsEncrypted clears the value of the "secrets_encrypted" field.
func (_u *VMUpdate) ClearSecretsEncrypted() *VMUpdate {
	_u.mutation.ClearSecretsEncrypted()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *VMUpdate) SetLastError(v string) *VMUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *VMUpdate) SetNillableLastError(v *string) *VMUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetEndpoints sets the "endpoints" field.
func (_u *VMUpdate) SetEndpoints(v json.RawMessage) *VMUpdate {
	_u.mutation.SetEndpoints(v)
	return _u
}

// AppendEndpoints appends value to the "endpoints" field.
func (_u *VMUpdate) AppendEndpoints(v json.RawMessage) *VMUpdate {
	_u.mutation.AppendEndpoints(v)
	return _u
}

// ClearEndpoints clears the value of the "endpoints" field.
func (_u *VMUpdate) ClearEndpoints() *VMUpdate {
	_u.mutation.ClearEndpoints()
	return _u
}

// SetGpus sets the "gpus" field.
func (_u *VMUpdate) SetGpus(v int32) *VMUpdate {
	_u.mutation.ResetGpus()
	_u.mutation.SetGpus(v)
	return _u
}

// SetNillableGpus sets the "gpus" field if the given value is not nil.
func (_u *VMUpdate) SetNillableGpus(v *int32) *VMUpdate {
	if v != nil {
		_u.SetGpus(*v)
	}
	return _u
}

// AddGpus adds value to the "gpus" field.
func (_u *VMUpdate) AddGpus(v int32) *VMUpdate {
	_u.mutation.AddGpus(v)
	return _u
}

// SetGpuKind sets the "gpu_kind" field.
func (_u *VMUpdate) SetGpuKind(v string) *VMUpdate {
	_u.mutation.SetGpuKind(v)
	return _u
}

// SetNillableGpuKind sets the "gpu_kind" field if the given value is not nil.
func (_u *VMUpdate) SetNillableGpuKind(v *string) *VMUpdate {
	if v != nil {
		_u.SetGpuKind(*v)
	}
	return _u
}

// SetGpuProfile sets the "gpu_profile" field.
func (_u *VMUpdate) SetGpuProfile(v string) *VMUpdate {
	_u.mutation.SetGpuProfile(v)
	return _u
}

// SetNillableGpuProfile sets the "gpu_profile" field if the given value is not nil.
func (_u *VMUpdate) SetNillableGpuProfile(v *string) *VMUpdate {
	if v != nil {
		_u.SetGpuProfile(*v)
	}
	return _u
}

// SetGpuUuids sets the "gpu_uuids" field.
func (_u *VMUpdate) SetGpuUuids(v json.RawMessage) *VMUpdate {
	_u.mutation.SetGpuUuids(v)
	return _u
}

// AppendGpuUuids appends value to the "gpu_uuids" field.
func (_u *VMUpdate) AppendGpuUuids(v json.RawMessage) *VMUpdate {
	_u.mutation.AppendGpuUuids(v)
	return _u
}

// ClearGpuUuids clears the value of the "gpu_uuids" field.
func (_u *VMUpdate) ClearGpuUuids() *VMUpdate {
	_u.mutation.ClearGpuUuids()
	return _u
}

// SetMigInstanceUuids sets the "mig_instance_uuids" field.
func (_u *VMUpdate) SetMigInstanceUuids(v json.RawMessage) *VMUpdate {
	_u.mutation.SetMigInstanceUuids(v)
	return _u
}

// AppendMigInstanceUuids appends value to the "mig_instance_uuids" field.
func (_u *VMUpdate) AppendMigInstanceUuids(v json.RawMessage) *VMUpdate {
	_u.mutation.AppendMigInstanceUuids(v)
	return _u
}

// ClearMigInstanceUuids clears the value of the "mig_instance_uuids" field.
func (_u *VMUpdate) ClearMigInstanceUuids() *VMUpdate {
	_u.mutation.ClearMigInstanceUuids()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *VMUpdate) SetCreatedAt(v time.Time) *VMUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *VMUpdate) SetNillableCreatedAt(v *time.Time) *VMUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VMUpdate) SetUpdatedAt(v time.Time) *VMUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *VMUpdate) SetNillableUpdatedAt(v *time.Time) *VMUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the VMMutation object of the builder.
func (_u *VMUpdate) Mutation() *VMMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VMUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VMUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VMUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VMUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VMUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := vm.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "VM.state": %w`, err)}
		}
	}
	return nil
}

func (_u *VMUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vm.Table, vm.Columns, sqlgraph.NewFieldSpec(vm.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.HostID(); ok {
		_spec.SetField(vm.FieldHostID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NetworkHost(); ok {
		_spec.SetField(vm.FieldNetworkHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(vm.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(vm.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(vm.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(vm.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cpus(); ok {
		_spec.SetField(vm.FieldCpus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCpus(); ok {
		_spec.AddField(vm.FieldCpus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RAMMB(); ok {
		_spec.SetField(vm.FieldRAMMB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRAMMB(); ok {
		_spec.AddField(vm.FieldRAMMB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StorageGB(); ok {
		_spec.SetField(vm.FieldStorageGB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStorageGB(); ok {
		_spec.AddField(vm.FieldStorageGB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(vm.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxRuntimeSeconds(); ok {
		_spec.SetField(vm.FieldMaxRuntimeSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRuntimeSeconds(); ok {
		_spec.AddField(vm.FieldMaxRuntimeSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IdleTimeoutSeconds(); ok {
		_spec.SetField(vm.FieldIdleTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIdleTimeoutSeconds(); ok {
		_spec.AddField(vm.FieldIdleTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AuthTokenEncrypted(); ok {
		_spec.SetField(vm.FieldAuthTokenEncrypted, field.TypeBytes, value)
	}
	if _u.mutation.AuthTokenEncryptedCleared() {
		_spec.ClearField(vm.FieldAuthTokenEncrypted, field.TypeBytes)
	}
	if value, ok := _u.mutation.SecretsEncrypted(); ok {
		_spec.SetField(vm.FieldSecretsEncrypted, field.TypeBytes, value)
	}
	if _u.mutation.SecretsEncryptedCleared() {
		_spec.ClearField(vm.FieldSecretsEncrypted, field.TypeBytes)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(vm.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoints(); ok {
		_spec.SetField(vm.FieldEndpoints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEndpoints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, vm.FieldEndpoints, value)
		})
	}
	if _u.mutation.EndpointsCleared() {
		_spec.ClearField(vm.FieldEndpoints, field.TypeJSON)
	}
	if value, ok := _u.mutation.Gpus(); ok {
		_spec.SetField(vm.FieldGpus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedGpus(); ok {
		_spec.AddField(vm.FieldGpus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.GpuKind(); ok {
		_spec.SetField(vm.FieldGpuKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.GpuProfile(); ok {
		_spec.SetField(vm.FieldGpuProfile, field.TypeString, value)
	}
	if value, ok := _u.mutation.GpuUuids(); ok {
		_spec.SetField(vm.FieldGpuUuids, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGpuUuids(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, vm.FieldGpuUuids, value)
		})
	}
	if _u.mutation.GpuUuidsCleared() {
		_spec.ClearField(vm.FieldGpuUuids, field.TypeJSON)
	}
	if value, ok := _u.mutation.MigInstanceUuids(); ok {
		_spec.SetField(vm.FieldMigInstanceUuids, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMigInstanceUuids(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, vm.FieldMigInstanceUuids, value)
		})
	}
	if _u.mutation.MigInstanceUuidsCleared() {
		_spec.ClearField(vm.FieldMigInstanceUuids, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(vm.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(vm.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vm.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VMUpdateOne is the builder for updating a single VM entity.
type VMUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VMMutation
}

// SetHostID sets the "host_id" field.
func (_u *VMUpdateOne) SetHostID(v string) *VMUpdateOne {
	_u.mutation.SetHostID(v)
	return _u
}

// SetNillableHostID sets the "host_id" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableHostID(v *string) *VMUpdateOne {
	if v != nil {
		_u.SetHostID(*v)
	}
	return _u
}

// SetNetworkHost sets the "network_host" field.
func (_u *VMUpdateOne) SetNetworkHost(v string) *VMUpdateOne {
	_u.mutation.SetNetworkHost(v)
	return _u
}

// SetNillableNetworkHost sets the "network_host" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableNetworkHost(v *string) *VMUpdateOne {
	if v != nil {
		_u.SetNetworkHost(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *VMUpdateOne) SetState(v vm.State) *VMUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableState(v *vm.State) *VMUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *VMUpdateOne) SetURL(v string) *VMUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableURL(v *string) *VMUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *VMUpdateOne) SetTaskID(v string) *VMUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableTaskID(v *string) *VMUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *VMUpdateOne) SetTenantID(v string) *VMUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableTenantID(v *string) *VMUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCpus sets the "cpus" field.
func (_u *VMUpdateOne) SetCpus(v int) *VMUpdateOne {
	_u.mutation.ResetCpus()
	_u.mutation.SetCpus(v)
	return _u
}

// SetNillableCpus sets the "cpus" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableCpus(v *int) *VMUpdateOne {
	if v != nil {
		_u.SetCpus(*v)
	}
	return _u
}

// AddCpus adds value to the "cpus" field.
func (_u *VMUpdateOne) AddCpus(v int) *VMUpdateOne {
	_u.mutation.AddCpus(v)
	return _u
}

// SetRAMMB sets the "ram_mb" field.
func (_u *VMUpdateOne) SetRAMMB(v int) *VMUpdateOne {
	_u.mutation.ResetRAMMB()
	_u.mutation.SetRAMMB(v)
	return _u
}

// SetNillableRAMMB sets the "ram_mb" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableRAMMB(v *int) *VMUpdateOne {
	if v != nil {
		_u.SetRAMMB(*v)
	}
	return _u
}

// AddRAMMB adds value to the "ram_mb" field.
func (_u *VMUpdateOne) AddRAMMB(v int) *VMUpdateOne {
	_u.mutation.AddRAMMB(v)
	return _u
}

// SetStorageGB sets the "storage_gb" field.
func (_u *VMUpdateOne) SetStorageGB(v int) *VMUpdateOne {
	_u.mutation.ResetStorageGB()
	_u.mutation.SetStorageGB(v)
	return _u
}

// SetNillableStorageGB sets the "storage_gb" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableStorageGB(v *int) *VMUpdateOne {
	if v != nil {
		_u.SetStorageGB(*v)
	}
	return _u
}

// AddStorageGB adds value to the "storage_gb" field.
func (_u *VMUpdateOne) AddStorageGB(v int) *VMUpdateOne {
	_u.mutation.AddStorageGB(v)
	return _u
}

// SetRegion sets the "region" field.
func (_u *VMUpdateOne) SetRegion(v string) *VMUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableRegion(v *string) *VMUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetMaxRuntimeSeconds sets the "max_runtime_seconds" field.
func (_u *VMUpdateOne) SetMaxRuntimeSeconds(v int) *VMUpdateOne {
	_u.mutation.ResetMaxRuntimeSeconds()
	_u.mutation.SetMaxRuntimeSeconds(v)
	return _u
}

// SetNillableMaxRuntimeSeconds sets the "max_runtime_seconds" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableMaxRuntimeSeconds(v *int) *VMUpdateOne {
	if v != nil {
		_u.SetMaxRuntimeSeconds(*v)
	}
	return _u
}

// AddMaxRuntimeSeconds adds value to the "max_runtime_seconds" field.
func (_u *VMUpdateOne) AddMaxRuntimeSeconds(v int) *VMUpdateOne {
	_u.mutation.AddMaxRuntimeSeconds(v)
	return _u
}

// SetIdleTimeoutSeconds sets the "idle_timeout_seconds" field.
func (_u *VMUpdateOne) SetIdleTimeoutSeconds(v int) *VMUpdateOne {
	_u.mutation.ResetIdleTimeoutSeconds()
	_u.mutation.SetIdleTimeoutSeconds(v)
	return _u
}

// SetNillableIdleTimeoutSeconds sets the "idle_timeout_seconds" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableIdleTimeoutSeconds(v *int) *VMUpdateOne {
	if v != nil {
		_u.SetIdleTimeoutSeconds(*v)
	}
	return _u
}

// AddIdleTimeoutSeconds adds value to the "idle_timeout_seconds" field.
func (_u *VMUpdateOne) AddIdleTimeoutSeconds(v int) *VMUpdateOne {
	_u.mutation.AddIdleTimeoutSeconds(v)
	return _u
}

// SetAuthTokenEncrypted sets the "auth_token_encrypted" field.
func (_u *VMUpdateOne) SetAuthTokenEncrypted(v []byte) *VMUpdateOne {
	_u.mutation.SetAuthTokenEncrypted(v)
	return _u
}

// ClearAuthTokenEncrypted clears the value of the "auth_token_encrypted" field.
func (_u *VMUpdateOne) ClearAuthTokenEncrypted() *VMUpdateOne {
	_u.mutation.ClearAuthTokenEncrypted()
	return _u
}

// SetSecretsEncrypted sets the "secrets_encrypted" field.
func (_u *VMUpdateOne) SetSecretsEncrypted(v []byte) *VMUpdateOne {
	_u.mutation.SetSecretsEncrypted(v)
	return _u
}

// ClearSecretsEncrypted clears the value of the "secrets_encrypted" field.
func (_u *VMUpdateOne) ClearSecretsEncrypted() *VMUpdateOne {
	_u.mutation.ClearSecretsEncrypted()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *VMUpdateOne) SetLastError(v string) *VMUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableLastError(v *string) *VMUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetEndpoints sets the "endpoints" field.
func (_u *VMUpdateOne) SetEndpoints(v json.RawMessage) *VMUpdateOne {
	_u.mutation.SetEndpoints(v)
	return _u
}

// AppendEndpoints appends value to the "endpoints" field.
func (_u *VMUpdateOne) AppendEndpoints(v json.RawMessage) *VMUpdateOne {
	_u.mutation.AppendEndpoints(v)
	return _u
}

// ClearEndpoints clears the value of the "endpoints" field.
func (_u *VMUpdateOne) ClearEndpoints() *VMUpdateOne {
	_u.mutation.ClearEndpoints()
	return _u
}

// SetGpus sets the "gpus" field.
func (_u *VMUpdateOne) SetGpus(v int32) *VMUpdateOne {
	_u.mutation.ResetGpus()
	_u.mutation.SetGpus(v)
	return _u
}

// SetNillableGpus sets the "gpus" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableGpus(v *int32) *VMUpdateOne {
	if v != nil {
		_u.SetGpus(*v)
	}
	return _u
}

// AddGpus adds value to the "gpus" field.
func (_u *VMUpdateOne) AddGpus(v int32) *VMUpdateOne {
	_u.mutation.AddGpus(v)
	return _u
}

// SetGpuKind sets the "gpu_kind" field.
func (_u *VMUpdateOne) SetGpuKind(v string) *VMUpdateOne {
	_u.mutation.SetGpuKind(v)
	return _u
}

// SetNillableGpuKind sets the "gpu_kind" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableGpuKind(v *string) *VMUpdateOne {
	if v != nil {
		_u.SetGpuKind(*v)
	}
	return _u
}

// SetGpuProfile sets the "gpu_profile" field.
func (_u *VMUpdateOne) SetGpuProfile(v string) *VMUpdateOne {
	_u.mutation.SetGpuProfile(v)
	return _u
}

// SetNillableGpuProfile sets the "gpu_profile" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableGpuProfile(v *string) *VMUpdateOne {
	if v != nil {
		_u.SetGpuProfile(*v)
	}
	return _u
}

// SetGpuUuids sets the "gpu_uuids" field.
func (_u *VMUpdateOne) SetGpuUuids(v json.RawMessage) *VMUpdateOne {
	_u.mutation.SetGpuUuids(v)
	return _u
}

// AppendGpuUuids appends value to the "gpu_uuids" field.
func (_u *VMUpdateOne) AppendGpuUuids(v json.RawMessage) *VMUpdateOne {
	_u.mutation.AppendGpuUuids(v)
	return _u
}

// ClearGpuUuids clears the value of the "gpu_uuids" field.
func (_u *VMUpdateOne) ClearGpuUuids() *VMUpdateOne {
	_u.mutation.ClearGpuUuids()
	return _u
}

// SetMigInstanceUuids sets the "mig_instance_uuids" field.
func (_u *VMUpdateOne) SetMigInstanceUuids(v json.RawMessage) *VMUpdateOne {
	_u.mutation.SetMigInstanceUuids(v)
	return _u
}

// AppendMigInstanceUuids appends value to the "mig_instance_uuids" field.
func (_u *VMUpdateOne) AppendMigInstanceUuids(v json.RawMessage) *VMUpdateOne {
	_u.mutation.AppendMigInstanceUuids(v)
	return _u
}

// ClearMigInstanceUuids clears the value of the "mig_instance_uuids" field.
func (_u *VMUpdateOne) ClearMigInstanceUuids() *VMUpdateOne {
	_u.mutation.ClearMigInstanceUuids()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *VMUpdateOne) SetCreatedAt(v time.Time) *VMUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableCreatedAt(v *time.Time) *VMUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VMUpdateOne) SetUpdatedAt(v time.Time) *VMUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *VMUpdateOne) SetNillableUpdatedAt(v *time.Time) *VMUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the VMMutation object of the builder.
func (_u *VMUpdateOne) Mutation() *VMMutation {
	return _u.mutation
}

// Where appends a list predicates to the VMUpdate builder.
func (_u *VMUpdateOne) Where(ps ...predicate.VM) *VMUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VMUpdateOne) Select(field string, fields ...string) *VMUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VM entity.
func (_u *VMUpdateOne) Save(ctx context.Context) (*VM, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VMUpdateOne) SaveX(ctx context.Context) *VM {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VMUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VMUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VMUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := vm.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "VM.state": %w`, err)}
		}
	}
	return nil
}

func (_u *VMUpdateOne) sqlSave(ctx context.Context) (_node *VM, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vm.Table, vm.Columns, sqlgraph.NewFieldSpec(vm.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VM.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vm.FieldID)
		for _, f := range fields {
			if !vm.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vm.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.HostID(); ok {
		_spec.SetField(vm.FieldHostID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NetworkHost(); ok {
		_spec.SetField(vm.FieldNetworkHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(vm.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(vm.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(vm.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(vm.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cpus(); ok {
		_spec.SetField(vm.FieldCpus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCpus(); ok {
		_spec.AddField(vm.FieldCpus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RAMMB(); ok {
		_spec.SetField(vm.FieldRAMMB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRAMMB(); ok {
		_spec.AddField(vm.FieldRAMMB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StorageGB(); ok {
		_spec.SetField(vm.FieldStorageGB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStorageGB(); ok {
		_spec.AddField(vm.FieldStorageGB, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(vm.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxRuntimeSeconds(); ok {
		_spec.SetField(vm.FieldMaxRuntimeSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRuntimeSeconds(); ok {
		_spec.AddField(vm.FieldMaxRuntimeSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IdleTimeoutSeconds(); ok {
		_spec.SetField(vm.FieldIdleTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIdleTimeoutSeconds(); ok {
		_spec.AddField(vm.FieldIdleTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AuthTokenEncrypted(); ok {
		_spec.SetField(vm.FieldAuthTokenEncrypted, field.TypeBytes, value)
	}
	if _u.mutation.AuthTokenEncryptedCleared() {
		_spec.ClearField(vm.FieldAuthTokenEncrypted, field.TypeBytes)
	}
	if value, ok := _u.mutation.SecretsEncrypted(); ok {
		_spec.SetField(vm.FieldSecretsEncrypted, field.TypeBytes, value)
	}
	if _u.mutation.SecretsEncryptedCleared() {
		_spec.ClearField(vm.FieldSecretsEncrypted, field.TypeBytes)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(vm.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoints(); ok {
		_spec.SetField(vm.FieldEndpoints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEndpoints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, vm.FieldEndpoints, value)
		})
	}
	if _u.mutation.EndpointsCleared() {
		_spec.ClearField(vm.FieldEndpoints, field.TypeJSON)
	}
	if value, ok := _u.mutation.Gpus(); ok {
		_spec.SetField(vm.FieldGpus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedGpus(); ok {
		_spec.AddField(vm.FieldGpus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.GpuKind(); ok {
		_spec.SetField(vm.FieldGpuKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.GpuProfile(); ok {
		_spec.SetField(vm.FieldGpuProfile, field.TypeString, value)
	}
	if value, ok := _u.mutation.GpuUuids(); ok {
		_spec.SetField(vm.FieldGpuUuids, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGpuUuids(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, vm.FieldGpuUuids, value)
		})
	}
	if _u.mutation.GpuUuidsCleared() {
		_spec.ClearField(vm.FieldGpuUuids, field.TypeJSON)
	}
	if value, ok := _u.mutation.MigInstanceUuids(); ok {
		_spec.SetField(vm.FieldMigInstanceUuids, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMigInstanceUuids(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, vm.FieldMigInstanceUuids, value)
		})
	}
	if _u.mutation.MigInstanceUuidsCleared() {
		_spec.ClearField(vm.FieldMigInstanceUuids, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(vm.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(vm.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &VM{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vm.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
