// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)

// VM is the predicate function for vm builders.
type VM func(*sql.Selector)
