// Code generated by ent, DO NOT EDIT.

package host

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the host type in the database.
	Label = "host"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "host_id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldTokenEncrypted holds the string denoting the token_encrypted field in the database.
	FieldTokenEncrypted = "token_encrypted"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCpusTotal holds the string denoting the cpus_total field in the database.
	FieldCpusTotal = "cpus_total"
	// FieldRAMMBTotal holds the string denoting the ram_mb_total field in the database.
	FieldRAMMBTotal = "ram_mb_total"
	// FieldStorageGBTotal holds the string denoting the storage_gb_total field in the database.
	FieldStorageGBTotal = "storage_gb_total"
	// FieldVMCountMax holds the string denoting the vm_count_max field in the database.
	FieldVMCountMax = "vm_count_max"
	// FieldCpusAllocated holds the string denoting the cpus_allocated field in the database.
	FieldCpusAllocated = "cpus_allocated"
	// FieldRAMMBAllocated holds the string denoting the ram_mb_allocated field in the database.
	FieldRAMMBAllocated = "ram_mb_allocated"
	// FieldStorageGBAllocated holds the string denoting the storage_gb_allocated field in the database.
	FieldStorageGBAllocated = "storage_gb_allocated"
	// FieldVMCountAllocated holds the string denoting the vm_count_allocated field in the database.
	FieldVMCountAllocated = "vm_count_allocated"
	// FieldLabels holds the string denoting the labels field in the database.
	FieldLabels = "labels_json"
	// FieldArch holds the string denoting the arch field in the database.
	FieldArch = "arch"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the host in the database.
	Table = "orchestrator_hosts"
)

// Columns holds all SQL columns for host fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldTokenEncrypted,
	FieldRegion,
	FieldState,
	FieldTenantID,
	FieldCpusTotal,
	FieldRAMMBTotal,
	FieldStorageGBTotal,
	FieldVMCountMax,
	FieldCpusAllocated,
	FieldRAMMBAllocated,
	FieldStorageGBAllocated,
	FieldVMCountAllocated,
	FieldLabels,
	FieldArch,
	FieldLastSeenAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRegion holds the default value on creation for the "region" field.
	DefaultRegion string
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID string
	// DefaultCpusTotal holds the default value on creation for the "cpus_total" field.
	DefaultCpusTotal int
	// DefaultRAMMBTotal holds the default value on creation for the "ram_mb_total" field.
	DefaultRAMMBTotal int
	// DefaultStorageGBTotal holds the default value on creation for the "storage_gb_total" field.
	DefaultStorageGBTotal int
	// DefaultVMCountMax holds the default value on creation for the "vm_count_max" field.
	DefaultVMCountMax int
	// DefaultCpusAllocated holds the default value on creation for the "cpus_allocated" field.
	DefaultCpusAllocated int
	// DefaultRAMMBAllocated holds the default value on creation for the "ram_mb_allocated" field.
	DefaultRAMMBAllocated int
	// DefaultStorageGBAllocated holds the default value on creation for the "storage_gb_allocated" field.
	DefaultStorageGBAllocated int
	// DefaultVMCountAllocated holds the default value on creation for the "vm_count_allocated" field.
	DefaultVMCountAllocated int
	// DefaultLabels holds the default value on creation for the "labels" field.
	DefaultLabels map[string]string
	// DefaultArch holds the default value on creation for the "arch" field.
	DefaultArch string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// State defines the type for the "state" enum field.
type State string

// StateActive is the default value of the State enum.
const DefaultState = StateActive

// State values.
const (
	StateActive   State = "active"
	StateCordoned State = "cordoned"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateActive, StateCordoned:
		return nil
	default:
		return fmt.Errorf("host: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the Host queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCpusTotal orders the results by the cpus_total field.
func ByCpusTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCpusTotal, opts...).ToFunc()
}

// ByRAMMBTotal orders the results by the ram_mb_total field.
func ByRAMMBTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRAMMBTotal, opts...).ToFunc()
}

// ByStorageGBTotal orders the results by the storage_gb_total field.
func ByStorageGBTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageGBTotal, opts...).ToFunc()
}

// ByVMCountMax orders the results by the vm_count_max field.
func ByVMCountMax(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVMCountMax, opts...).ToFunc()
}

// ByCpusAllocated orders the results by the cpus_allocated field.
func ByCpusAllocated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCpusAllocated, opts...).ToFunc()
}

// ByRAMMBAllocated orders the results by the ram_mb_allocated field.
func ByRAMMBAllocated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRAMMBAllocated, opts...).ToFunc()
}

// ByStorageGBAllocated orders the results by the storage_gb_allocated field.
func ByStorageGBAllocated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageGBAllocated, opts...).ToFunc()
}

// ByVMCountAllocated orders the results by the vm_count_allocated field.
func ByVMCountAllocated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVMCountAllocated, opts...).ToFunc()
}

// ByArch orders the results by the arch field.
func ByArch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArch, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
