// Code generated by ent, DO NOT EDIT.

package host

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/folsomintel/fuse/internal/entspike/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Host {
	return predicate.Host(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Host {
	return predicate.Host(sql.FieldContainsFold(FieldID, id))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldURL, v))
}

// TokenEncrypted applies equality check predicate on the "token_encrypted" field. It's identical to TokenEncryptedEQ.
func TokenEncrypted(v []byte) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldTokenEncrypted, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldRegion, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldTenantID, v))
}

// CpusTotal applies equality check predicate on the "cpus_total" field. It's identical to CpusTotalEQ.
func CpusTotal(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldCpusTotal, v))
}

// RAMMBTotal applies equality check predicate on the "ram_mb_total" field. It's identical to RAMMBTotalEQ.
func RAMMBTotal(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldRAMMBTotal, v))
}

// StorageGBTotal applies equality check predicate on the "storage_gb_total" field. It's identical to StorageGBTotalEQ.
func StorageGBTotal(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldStorageGBTotal, v))
}

// VMCountMax applies equality check predicate on the "vm_count_max" field. It's identical to VMCountMaxEQ.
func VMCountMax(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldVMCountMax, v))
}

// CpusAllocated applies equality check predicate on the "cpus_allocated" field. It's identical to CpusAllocatedEQ.
func CpusAllocated(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldCpusAllocated, v))
}

// RAMMBAllocated applies equality check predicate on the "ram_mb_allocated" field. It's identical to RAMMBAllocatedEQ.
func RAMMBAllocated(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldRAMMBAllocated, v))
}

// StorageGBAllocated applies equality check predicate on the "storage_gb_allocated" field. It's identical to StorageGBAllocatedEQ.
func StorageGBAllocated(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldStorageGBAllocated, v))
}

// VMCountAllocated applies equality check predicate on the "vm_count_allocated" field. It's identical to VMCountAllocatedEQ.
func VMCountAllocated(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldVMCountAllocated, v))
}

// Arch applies equality check predicate on the "arch" field. It's identical to ArchEQ.
func Arch(v string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldArch, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldUpdatedAt, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Host {
	return predicate.Host(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Host {
	return predicate.Host(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Host {
	return predicate.Host(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Host {
	return predicate.Host(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Host {
	return predicate.Host(sql.FieldContainsFold(FieldURL, v))
}

// TokenEncryptedEQ applies the EQ predicate on the "token_encrypted" field.
func TokenEncryptedEQ(v []byte) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldTokenEncrypted, v))
}

// TokenEncryptedNEQ applies the NEQ predicate on the "token_encrypted" field.
func TokenEncryptedNEQ(v []byte) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldTokenEncrypted, v))
}

// TokenEncryptedIn applies the In predicate on the "token_encrypted" field.
func TokenEncryptedIn(vs ...[]byte) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldTokenEncrypted, vs...))
}

// TokenEncryptedNotIn applies the NotIn predicate on the "token_encrypted" field.
func TokenEncryptedNotIn(vs ...[]byte) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldTokenEncrypted, vs...))
}

// TokenEncryptedGT applies the GT predicate on the "token_encrypted" field.
func TokenEncryptedGT(v []byte) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldTokenEncrypted, v))
}

// TokenEncryptedGTE applies the GTE predicate on the "token_encrypted" field.
func TokenEncryptedGTE(v []byte) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldTokenEncrypted, v))
}

// TokenEncryptedLT applies the LT predicate on the "token_encrypted" field.
func TokenEncryptedLT(v []byte) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldTokenEncrypted, v))
}

// TokenEncryptedLTE applies the LTE predicate on the "token_encrypted" field.
func TokenEncryptedLTE(v []byte) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldTokenEncrypted, v))
}

// TokenEncryptedIsNil applies the IsNil predicate on the "token_encrypted" field.
func TokenEncryptedIsNil() predicate.Host {
	return predicate.Host(sql.FieldIsNull(FieldTokenEncrypted))
}

// TokenEncryptedNotNil applies the NotNil predicate on the "token_encrypted" field.
func TokenEncryptedNotNil() predicate.Host {
	return predicate.Host(sql.FieldNotNull(FieldTokenEncrypted))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.Host {
	return predicate.Host(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.Host {
	return predicate.Host(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.Host {
	return predicate.Host(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.Host {
	return predicate.Host(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.Host {
	return predicate.Host(sql.FieldContainsFold(FieldRegion, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldState, vs...))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.Host {
	return predicate.Host(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.Host {
	return predicate.Host(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.Host {
	return predicate.Host(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.Host {
	return predicate.Host(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.Host {
	return predicate.Host(sql.FieldContainsFold(FieldTenantID, v))
}

// CpusTotalEQ applies the EQ predicate on the "cpus_total" field.
func CpusTotalEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldCpusTotal, v))
}

// CpusTotalNEQ applies the NEQ predicate on the "cpus_total" field.
func CpusTotalNEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldCpusTotal, v))
}

// CpusTotalIn applies the In predicate on the "cpus_total" field.
func CpusTotalIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldCpusTotal, vs...))
}

// CpusTotalNotIn applies the NotIn predicate on the "cpus_total" field.
func CpusTotalNotIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldCpusTotal, vs...))
}

// CpusTotalGT applies the GT predicate on the "cpus_total" field.
func CpusTotalGT(v int) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldCpusTotal, v))
}

// CpusTotalGTE applies the GTE predicate on the "cpus_total" field.
func CpusTotalGTE(v int) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldCpusTotal, v))
}

// CpusTotalLT applies the LT predicate on the "cpus_total" field.
func CpusTotalLT(v int) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldCpusTotal, v))
}

// CpusTotalLTE applies the LTE predicate on the "cpus_total" field.
func CpusTotalLTE(v int) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldCpusTotal, v))
}

// RAMMBTotalEQ applies the EQ predicate on the "ram_mb_total" field.
func RAMMBTotalEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldRAMMBTotal, v))
}

// RAMMBTotalNEQ applies the NEQ predicate on the "ram_mb_total" field.
func RAMMBTotalNEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldRAMMBTotal, v))
}

// RAMMBTotalIn applies the In predicate on the "ram_mb_total" field.
func RAMMBTotalIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldRAMMBTotal, vs...))
}

// RAMMBTotalNotIn applies the NotIn predicate on the "ram_mb_total" field.
func RAMMBTotalNotIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldRAMMBTotal, vs...))
}

// RAMMBTotalGT applies the GT predicate on the "ram_mb_total" field.
func RAMMBTotalGT(v int) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldRAMMBTotal, v))
}

// RAMMBTotalGTE applies the GTE predicate on the "ram_mb_total" field.
func RAMMBTotalGTE(v int) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldRAMMBTotal, v))
}

// RAMMBTotalLT applies the LT predicate on the "ram_mb_total" field.
func RAMMBTotalLT(v int) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldRAMMBTotal, v))
}

// RAMMBTotalLTE applies the LTE predicate on the "ram_mb_total" field.
func RAMMBTotalLTE(v int) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldRAMMBTotal, v))
}

// StorageGBTotalEQ applies the EQ predicate on the "storage_gb_total" field.
func StorageGBTotalEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldStorageGBTotal, v))
}

// StorageGBTotalNEQ applies the NEQ predicate on the "storage_gb_total" field.
func StorageGBTotalNEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldStorageGBTotal, v))
}

// StorageGBTotalIn applies the In predicate on the "storage_gb_total" field.
func StorageGBTotalIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldStorageGBTotal, vs...))
}

// StorageGBTotalNotIn applies the NotIn predicate on the "storage_gb_total" field.
func StorageGBTotalNotIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldStorageGBTotal, vs...))
}

// StorageGBTotalGT applies the GT predicate on the "storage_gb_total" field.
func StorageGBTotalGT(v int) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldStorageGBTotal, v))
}

// StorageGBTotalGTE applies the GTE predicate on the "storage_gb_total" field.
func StorageGBTotalGTE(v int) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldStorageGBTotal, v))
}

// StorageGBTotalLT applies the LT predicate on the "storage_gb_total" field.
func StorageGBTotalLT(v int) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldStorageGBTotal, v))
}

// StorageGBTotalLTE applies the LTE predicate on the "storage_gb_total" field.
func StorageGBTotalLTE(v int) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldStorageGBTotal, v))
}

// VMCountMaxEQ applies the EQ predicate on the "vm_count_max" field.
func VMCountMaxEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldVMCountMax, v))
}

// VMCountMaxNEQ applies the NEQ predicate on the "vm_count_max" field.
func VMCountMaxNEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldVMCountMax, v))
}

// VMCountMaxIn applies the In predicate on the "vm_count_max" field.
func VMCountMaxIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldVMCountMax, vs...))
}

// VMCountMaxNotIn applies the NotIn predicate on the "vm_count_max" field.
func VMCountMaxNotIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldVMCountMax, vs...))
}

// VMCountMaxGT applies the GT predicate on the "vm_count_max" field.
func VMCountMaxGT(v int) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldVMCountMax, v))
}

// VMCountMaxGTE applies the GTE predicate on the "vm_count_max" field.
func VMCountMaxGTE(v int) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldVMCountMax, v))
}

// VMCountMaxLT applies the LT predicate on the "vm_count_max" field.
func VMCountMaxLT(v int) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldVMCountMax, v))
}

// VMCountMaxLTE applies the LTE predicate on the "vm_count_max" field.
func VMCountMaxLTE(v int) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldVMCountMax, v))
}

// CpusAllocatedEQ applies the EQ predicate on the "cpus_allocated" field.
func CpusAllocatedEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldCpusAllocated, v))
}

// CpusAllocatedNEQ applies the NEQ predicate on the "cpus_allocated" field.
func CpusAllocatedNEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldCpusAllocated, v))
}

// CpusAllocatedIn applies the In predicate on the "cpus_allocated" field.
func CpusAllocatedIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldCpusAllocated, vs...))
}

// CpusAllocatedNotIn applies the NotIn predicate on the "cpus_allocated" field.
func CpusAllocatedNotIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldCpusAllocated, vs...))
}

// CpusAllocatedGT applies the GT predicate on the "cpus_allocated" field.
func CpusAllocatedGT(v int) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldCpusAllocated, v))
}

// CpusAllocatedGTE applies the GTE predicate on the "cpus_allocated" field.
func CpusAllocatedGTE(v int) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldCpusAllocated, v))
}

// CpusAllocatedLT applies the LT predicate on the "cpus_allocated" field.
func CpusAllocatedLT(v int) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldCpusAllocated, v))
}

// CpusAllocatedLTE applies the LTE predicate on the "cpus_allocated" field.
func CpusAllocatedLTE(v int) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldCpusAllocated, v))
}

// RAMMBAllocatedEQ applies the EQ predicate on the "ram_mb_allocated" field.
func RAMMBAllocatedEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldRAMMBAllocated, v))
}

// RAMMBAllocatedNEQ applies the NEQ predicate on the "ram_mb_allocated" field.
func RAMMBAllocatedNEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldRAMMBAllocated, v))
}

// RAMMBAllocatedIn applies the In predicate on the "ram_mb_allocated" field.
func RAMMBAllocatedIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldRAMMBAllocated, vs...))
}

// RAMMBAllocatedNotIn applies the NotIn predicate on the "ram_mb_allocated" field.
func RAMMBAllocatedNotIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldRAMMBAllocated, vs...))
}

// RAMMBAllocatedGT applies the GT predicate on the "ram_mb_allocated" field.
func RAMMBAllocatedGT(v int) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldRAMMBAllocated, v))
}

// RAMMBAllocatedGTE applies the GTE predicate on the "ram_mb_allocated" field.
func RAMMBAllocatedGTE(v int) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldRAMMBAllocated, v))
}

// RAMMBAllocatedLT applies the LT predicate on the "ram_mb_allocated" field.
func RAMMBAllocatedLT(v int) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldRAMMBAllocated, v))
}

// RAMMBAllocatedLTE applies the LTE predicate on the "ram_mb_allocated" field.
func RAMMBAllocatedLTE(v int) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldRAMMBAllocated, v))
}

// StorageGBAllocatedEQ applies the EQ predicate on the "storage_gb_allocated" field.
func StorageGBAllocatedEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldStorageGBAllocated, v))
}

// StorageGBAllocatedNEQ applies the NEQ predicate on the "storage_gb_allocated" field.
func StorageGBAllocatedNEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldStorageGBAllocated, v))
}

// StorageGBAllocatedIn applies the In predicate on the "storage_gb_allocated" field.
func StorageGBAllocatedIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldStorageGBAllocated, vs...))
}

// StorageGBAllocatedNotIn applies the NotIn predicate on the "storage_gb_allocated" field.
func StorageGBAllocatedNotIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldStorageGBAllocated, vs...))
}

// StorageGBAllocatedGT applies the GT predicate on the "storage_gb_allocated" field.
func StorageGBAllocatedGT(v int) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldStorageGBAllocated, v))
}

// StorageGBAllocatedGTE applies the GTE predicate on the "storage_gb_allocated" field.
func StorageGBAllocatedGTE(v int) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldStorageGBAllocated, v))
}

// StorageGBAllocatedLT applies the LT predicate on the "storage_gb_allocated" field.
func StorageGBAllocatedLT(v int) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldStorageGBAllocated, v))
}

// StorageGBAllocatedLTE applies the LTE predicate on the "storage_gb_allocated" field.
func StorageGBAllocatedLTE(v int) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldStorageGBAllocated, v))
}

// VMCountAllocatedEQ applies the EQ predicate on the "vm_count_allocated" field.
func VMCountAllocatedEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldVMCountAllocated, v))
}

// VMCountAllocatedNEQ applies the NEQ predicate on the "vm_count_allocated" field.
func VMCountAllocatedNEQ(v int) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldVMCountAllocated, v))
}

// VMCountAllocatedIn applies the In predicate on the "vm_count_allocated" field.
func VMCountAllocatedIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldVMCountAllocated, vs...))
}

// VMCountAllocatedNotIn applies the NotIn predicate on the "vm_count_allocated" field.
func VMCountAllocatedNotIn(vs ...int) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldVMCountAllocated, vs...))
}

// VMCountAllocatedGT applies the GT predicate on the "vm_count_allocated" field.
func VMCountAllocatedGT(v int) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldVMCountAllocated, v))
}

// VMCountAllocatedGTE applies the GTE predicate on the "vm_count_allocated" field.
func VMCountAllocatedGTE(v int) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldVMCountAllocated, v))
}

// VMCountAllocatedLT applies the LT predicate on the "vm_count_allocated" field.
func VMCountAllocatedLT(v int) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldVMCountAllocated, v))
}

// VMCountAllocatedLTE applies the LTE predicate on the "vm_count_allocated" field.
func VMCountAllocatedLTE(v int) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldVMCountAllocated, v))
}

// ArchEQ applies the EQ predicate on the "arch" field.
func ArchEQ(v string) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldArch, v))
}

// ArchNEQ applies the NEQ predicate on the "arch" field.
func ArchNEQ(v string) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldArch, v))
}

// ArchIn applies the In predicate on the "arch" field.
func ArchIn(vs ...string) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldArch, vs...))
}

// ArchNotIn applies the NotIn predicate on the "arch" field.
func ArchNotIn(vs ...string) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldArch, vs...))
}

// ArchGT applies the GT predicate on the "arch" field.
func ArchGT(v string) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldArch, v))
}

// ArchGTE applies the GTE predicate on the "arch" field.
func ArchGTE(v string) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldArch, v))
}

// ArchLT applies the LT predicate on the "arch" field.
func ArchLT(v string) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldArch, v))
}

// ArchLTE applies the LTE predicate on the "arch" field.
func ArchLTE(v string) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldArch, v))
}

// ArchContains applies the Contains predicate on the "arch" field.
func ArchContains(v string) predicate.Host {
	return predicate.Host(sql.FieldContains(FieldArch, v))
}

// ArchHasPrefix applies the HasPrefix predicate on the "arch" field.
func ArchHasPrefix(v string) predicate.Host {
	return predicate.Host(sql.FieldHasPrefix(FieldArch, v))
}

// ArchHasSuffix applies the HasSuffix predicate on the "arch" field.
func ArchHasSuffix(v string) predicate.Host {
	return predicate.Host(sql.FieldHasSuffix(FieldArch, v))
}

// ArchEqualFold applies the EqualFold predicate on the "arch" field.
func ArchEqualFold(v string) predicate.Host {
	return predicate.Host(sql.FieldEqualFold(FieldArch, v))
}

// ArchContainsFold applies the ContainsFold predicate on the "arch" field.
func ArchContainsFold(v string) predicate.Host {
	return predicate.Host(sql.FieldContainsFold(FieldArch, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Host) predicate.Host {
	return predicate.Host(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Host) predicate.Host {
	return predicate.Host(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Host) predicate.Host {
	return predicate.Host(sql.NotPredicates(p))
}
