// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrchestratorHostsColumns holds the columns for the "orchestrator_hosts" table.
	OrchestratorHostsColumns = []*schema.Column{
		{Name: "host_id", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "token_encrypted", Type: field.TypeBytes, Nullable: true},
		{Name: "region", Type: field.TypeString, Default: ""},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"active", "cordoned"}, Default: "active"},
		{Name: "tenant_id", Type: field.TypeString, Default: ""},
		{Name: "cpus_total", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "ram_mb_total", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "storage_gb_total", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "vm_count_max", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "cpus_allocated", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "ram_mb_allocated", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "storage_gb_allocated", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "vm_count_allocated", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "labels_json", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "arch", Type: field.TypeString, Default: ""},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OrchestratorHostsTable holds the schema information for the "orchestrator_hosts" table.
	OrchestratorHostsTable = &schema.Table{
		Name:       "orchestrator_hosts",
		Columns:    OrchestratorHostsColumns,
		PrimaryKey: []*schema.Column{OrchestratorHostsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "host_state",
				Unique:  false,
				Columns: []*schema.Column{OrchestratorHostsColumns[4]},
			},
			{
				Name:    "host_region",
				Unique:  false,
				Columns: []*schema.Column{OrchestratorHostsColumns[3]},
			},
			{
				Name:    "host_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{OrchestratorHostsColumns[5]},
			},
		},
	}
	// OrchestratorVmsColumns holds the columns for the "orchestrator_vms" table.
	OrchestratorVmsColumns = []*schema.Column{
		{Name: "vm_id", Type: field.TypeString},
		{Name: "host_id", Type: field.TypeString, Default: ""},
		{Name: "network_host", Type: field.TypeString, Default: ""},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"provisioning", "running", "draining", "destroying", "destroyed", "failed"}},
		{Name: "url", Type: field.TypeString, Default: ""},
		{Name: "task_id", Type: field.TypeString, Default: ""},
		{Name: "tenant_id", Type: field.TypeString, Default: ""},
		{Name: "cpus", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "ram_mb", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "storage_gb", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "region", Type: field.TypeString, Default: ""},
		{Name: "max_runtime_seconds", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "idle_timeout_seconds", Type: field.TypeInt, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "auth_token_encrypted", Type: field.TypeBytes, Nullable: true},
		{Name: "secrets_encrypted", Type: field.TypeBytes, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "endpoints_json", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "gpus", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "gpu_kind", Type: field.TypeString, Default: ""},
		{Name: "gpu_profile", Type: field.TypeString, Default: ""},
		{Name: "gpu_uuids", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "mig_instance_uuids", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OrchestratorVmsTable holds the schema information for the "orchestrator_vms" table.
	OrchestratorVmsTable = &schema.Table{
		Name:       "orchestrator_vms",
		Columns:    OrchestratorVmsColumns,
		PrimaryKey: []*schema.Column{OrchestratorVmsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "vm_state",
				Unique:  false,
				Columns: []*schema.Column{OrchestratorVmsColumns[3]},
			},
			{
				Name:    "vm_task_id",
				Unique:  false,
				Columns: []*schema.Column{OrchestratorVmsColumns[5]},
			},
			{
				Name:    "vm_host_id",
				Unique:  false,
				Columns: []*schema.Column{OrchestratorVmsColumns[1]},
			},
			{
				Name:    "vm_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{OrchestratorVmsColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrchestratorHostsTable,
		OrchestratorVmsTable,
	}
)

func init() {
	OrchestratorHostsTable.Annotation = &entsql.Annotation{
		Table: "orchestrator_hosts",
	}
	OrchestratorVmsTable.Annotation = &entsql.Annotation{
		Table: "orchestrator_vms",
	}
}
