// Code generated by ent, DO NOT EDIT.

package vm

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the vm type in the database.
	Label = "vm"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "vm_id"
	// FieldHostID holds the string denoting the host_id field in the database.
	FieldHostID = "host_id"
	// FieldNetworkHost holds the string denoting the network_host field in the database.
	FieldNetworkHost = "network_host"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCpus holds the string denoting the cpus field in the database.
	FieldCpus = "cpus"
	// FieldRAMMB holds the string denoting the ram_mb field in the database.
	FieldRAMMB = "ram_mb"
	// FieldStorageGB holds the string denoting the storage_gb field in the database.
	FieldStorageGB = "storage_gb"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldMaxRuntimeSeconds holds the string denoting the max_runtime_seconds field in the database.
	FieldMaxRuntimeSeconds = "max_runtime_seconds"
	// FieldIdleTimeoutSeconds holds the string denoting the idle_timeout_seconds field in the database.
	FieldIdleTimeoutSeconds = "idle_timeout_seconds"
	// FieldAuthTokenEncrypted holds the string denoting the auth_token_encrypted field in the database.
	FieldAuthTokenEncrypted = "auth_token_encrypted"
	// FieldSecretsEncrypted holds the string denoting the secrets_encrypted field in the database.
	FieldSecretsEncrypted = "secrets_encrypted"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldEndpoints holds the string denoting the endpoints field in the database.
	FieldEndpoints = "endpoints_json"
	// FieldGpus holds the string denoting the gpus field in the database.
	FieldGpus = "gpus"
	// FieldGpuKind holds the string denoting the gpu_kind field in the database.
	FieldGpuKind = "gpu_kind"
	// FieldGpuProfile holds the string denoting the gpu_profile field in the database.
	FieldGpuProfile = "gpu_profile"
	// FieldGpuUuids holds the string denoting the gpu_uuids field in the database.
	FieldGpuUuids = "gpu_uuids"
	// FieldMigInstanceUuids holds the string denoting the mig_instance_uuids field in the database.
	FieldMigInstanceUuids = "mig_instance_uuids"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the vm in the database.
	Table = "orchestrator_vms"
)

// Columns holds all SQL columns for vm fields.
var Columns = []string{
	FieldID,
	FieldHostID,
	FieldNetworkHost,
	FieldState,
	FieldURL,
	FieldTaskID,
	FieldTenantID,
	FieldCpus,
	FieldRAMMB,
	FieldStorageGB,
	FieldRegion,
	FieldMaxRuntimeSeconds,
	FieldIdleTimeoutSeconds,
	FieldAuthTokenEncrypted,
	FieldSecretsEncrypted,
	FieldLastError,
	FieldEndpoints,
	FieldGpus,
	FieldGpuKind,
	FieldGpuProfile,
	FieldGpuUuids,
	FieldMigInstanceUuids,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultHostID holds the default value on creation for the "host_id" field.
	DefaultHostID string
	// DefaultNetworkHost holds the default value on creation for the "network_host" field.
	DefaultNetworkHost string
	// DefaultURL holds the default value on creation for the "url" field.
	DefaultURL string
	// DefaultTaskID holds the default value on creation for the "task_id" field.
	DefaultTaskID string
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID string
	// DefaultCpus holds the default value on creation for the "cpus" field.
	DefaultCpus int
	// DefaultRAMMB holds the default value on creation for the "ram_mb" field.
	DefaultRAMMB int
	// DefaultStorageGB holds the default value on creation for the "storage_gb" field.
	DefaultStorageGB int
	// DefaultRegion holds the default value on creation for the "region" field.
	DefaultRegion string
	// DefaultMaxRuntimeSeconds holds the default value on creation for the "max_runtime_seconds" field.
	DefaultMaxRuntimeSeconds int
	// DefaultIdleTimeoutSeconds holds the default value on creation for the "idle_timeout_seconds" field.
	DefaultIdleTimeoutSeconds int
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultGpus holds the default value on creation for the "gpus" field.
	DefaultGpus int32
	// DefaultGpuKind holds the default value on creation for the "gpu_kind" field.
	DefaultGpuKind string
	// DefaultGpuProfile holds the default value on creation for the "gpu_profile" field.
	DefaultGpuProfile string
)

// State defines the type for the "state" enum field.
type State string

// State values.
const (
	StateProvisioning State = "provisioning"
	StateRunning      State = "running"
	StateDraining     State = "draining"
	StateDestroying   State = "destroying"
	StateDestroyed    State = "destroyed"
	StateFailed       State = "failed"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateProvisioning, StateRunning, StateDraining, StateDestroying, StateDestroyed, StateFailed:
		return nil
	default:
		return fmt.Errorf("vm: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the VM queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHostID orders the results by the host_id field.
func ByHostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostID, opts...).ToFunc()
}

// ByNetworkHost orders the results by the network_host field.
func ByNetworkHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetworkHost, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCpus orders the results by the cpus field.
func ByCpus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCpus, opts...).ToFunc()
}

// ByRAMMB orders the results by the ram_mb field.
func ByRAMMB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRAMMB, opts...).ToFunc()
}

// ByStorageGB orders the results by the storage_gb field.
func ByStorageGB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageGB, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByMaxRuntimeSeconds orders the results by the max_runtime_seconds field.
func ByMaxRuntimeSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxRuntimeSeconds, opts...).ToFunc()
}

// ByIdleTimeoutSeconds orders the results by the idle_timeout_seconds field.
func ByIdleTimeoutSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdleTimeoutSeconds, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByGpus orders the results by the gpus field.
func ByGpus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGpus, opts...).ToFunc()
}

// ByGpuKind orders the results by the gpu_kind field.
func ByGpuKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGpuKind, opts...).ToFunc()
}

// ByGpuProfile orders the results by the gpu_profile field.
func ByGpuProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGpuProfile, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
