// Code generated by ent, DO NOT EDIT.

package vm

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/folsomintel/fuse/internal/entspike/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldID, id))
}

// HostID applies equality check predicate on the "host_id" field. It's identical to HostIDEQ.
func HostID(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldHostID, v))
}

// NetworkHost applies equality check predicate on the "network_host" field. It's identical to NetworkHostEQ.
func NetworkHost(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldNetworkHost, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldURL, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldTaskID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldTenantID, v))
}

// Cpus applies equality check predicate on the "cpus" field. It's identical to CpusEQ.
func Cpus(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldCpus, v))
}

// RAMMB applies equality check predicate on the "ram_mb" field. It's identical to RAMMBEQ.
func RAMMB(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldRAMMB, v))
}

// StorageGB applies equality check predicate on the "storage_gb" field. It's identical to StorageGBEQ.
func StorageGB(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldStorageGB, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldRegion, v))
}

// MaxRuntimeSeconds applies equality check predicate on the "max_runtime_seconds" field. It's identical to MaxRuntimeSecondsEQ.
func MaxRuntimeSeconds(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldMaxRuntimeSeconds, v))
}

// IdleTimeoutSeconds applies equality check predicate on the "idle_timeout_seconds" field. It's identical to IdleTimeoutSecondsEQ.
func IdleTimeoutSeconds(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldIdleTimeoutSeconds, v))
}

// AuthTokenEncrypted applies equality check predicate on the "auth_token_encrypted" field. It's identical to AuthTokenEncryptedEQ.
func AuthTokenEncrypted(v []byte) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldAuthTokenEncrypted, v))
}

// SecretsEncrypted applies equality check predicate on the "secrets_encrypted" field. It's identical to SecretsEncryptedEQ.
func SecretsEncrypted(v []byte) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldSecretsEncrypted, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldLastError, v))
}

// Gpus applies equality check predicate on the "gpus" field. It's identical to GpusEQ.
func Gpus(v int32) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldGpus, v))
}

// GpuKind applies equality check predicate on the "gpu_kind" field. It's identical to GpuKindEQ.
func GpuKind(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldGpuKind, v))
}

// GpuProfile applies equality check predicate on the "gpu_profile" field. It's identical to GpuProfileEQ.
func GpuProfile(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldGpuProfile, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldUpdatedAt, v))
}

// HostIDEQ applies the EQ predicate on the "host_id" field.
func HostIDEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldHostID, v))
}

// HostIDNEQ applies the NEQ predicate on the "host_id" field.
func HostIDNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldHostID, v))
}

// HostIDIn applies the In predicate on the "host_id" field.
func HostIDIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldHostID, vs...))
}

// HostIDNotIn applies the NotIn predicate on the "host_id" field.
func HostIDNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldHostID, vs...))
}

// HostIDGT applies the GT predicate on the "host_id" field.
func HostIDGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldHostID, v))
}

// HostIDGTE applies the GTE predicate on the "host_id" field.
func HostIDGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldHostID, v))
}

// HostIDLT applies the LT predicate on the "host_id" field.
func HostIDLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldHostID, v))
}

// HostIDLTE applies the LTE predicate on the "host_id" field.
func HostIDLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldHostID, v))
}

// HostIDContains applies the Contains predicate on the "host_id" field.
func HostIDContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldHostID, v))
}

// HostIDHasPrefix applies the HasPrefix predicate on the "host_id" field.
func HostIDHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldHostID, v))
}

// HostIDHasSuffix applies the HasSuffix predicate on the "host_id" field.
func HostIDHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldHostID, v))
}

// HostIDEqualFold applies the EqualFold predicate on the "host_id" field.
func HostIDEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldHostID, v))
}

// HostIDContainsFold applies the ContainsFold predicate on the "host_id" field.
func HostIDContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldHostID, v))
}

// NetworkHostEQ applies the EQ predicate on the "network_host" field.
func NetworkHostEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldNetworkHost, v))
}

// NetworkHostNEQ applies the NEQ predicate on the "network_host" field.
func NetworkHostNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldNetworkHost, v))
}

// NetworkHostIn applies the In predicate on the "network_host" field.
func NetworkHostIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldNetworkHost, vs...))
}

// NetworkHostNotIn applies the NotIn predicate on the "network_host" field.
func NetworkHostNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldNetworkHost, vs...))
}

// NetworkHostGT applies the GT predicate on the "network_host" field.
func NetworkHostGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldNetworkHost, v))
}

// NetworkHostGTE applies the GTE predicate on the "network_host" field.
func NetworkHostGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldNetworkHost, v))
}

// NetworkHostLT applies the LT predicate on the "network_host" field.
func NetworkHostLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldNetworkHost, v))
}

// NetworkHostLTE applies the LTE predicate on the "network_host" field.
func NetworkHostLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldNetworkHost, v))
}

// NetworkHostContains applies the Contains predicate on the "network_host" field.
func NetworkHostContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldNetworkHost, v))
}

// NetworkHostHasPrefix applies the HasPrefix predicate on the "network_host" field.
func NetworkHostHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldNetworkHost, v))
}

// NetworkHostHasSuffix applies the HasSuffix predicate on the "network_host" field.
func NetworkHostHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldNetworkHost, v))
}

// NetworkHostEqualFold applies the EqualFold predicate on the "network_host" field.
func NetworkHostEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldNetworkHost, v))
}

// NetworkHostContainsFold applies the ContainsFold predicate on the "network_host" field.
func NetworkHostContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldNetworkHost, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldState, vs...))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldURL, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldTaskID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldTenantID, v))
}

// CpusEQ applies the EQ predicate on the "cpus" field.
func CpusEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldCpus, v))
}

// CpusNEQ applies the NEQ predicate on the "cpus" field.
func CpusNEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldCpus, v))
}

// CpusIn applies the In predicate on the "cpus" field.
func CpusIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldCpus, vs...))
}

// CpusNotIn applies the NotIn predicate on the "cpus" field.
func CpusNotIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldCpus, vs...))
}

// CpusGT applies the GT predicate on the "cpus" field.
func CpusGT(v int) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldCpus, v))
}

// CpusGTE applies the GTE predicate on the "cpus" field.
func CpusGTE(v int) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldCpus, v))
}

// CpusLT applies the LT predicate on the "cpus" field.
func CpusLT(v int) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldCpus, v))
}

// CpusLTE applies the LTE predicate on the "cpus" field.
func CpusLTE(v int) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldCpus, v))
}

// RAMMBEQ applies the EQ predicate on the "ram_mb" field.
func RAMMBEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldRAMMB, v))
}

// RAMMBNEQ applies the NEQ predicate on the "ram_mb" field.
func RAMMBNEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldRAMMB, v))
}

// RAMMBIn applies the In predicate on the "ram_mb" field.
func RAMMBIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldRAMMB, vs...))
}

// RAMMBNotIn applies the NotIn predicate on the "ram_mb" field.
func RAMMBNotIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldRAMMB, vs...))
}

// RAMMBGT applies the GT predicate on the "ram_mb" field.
func RAMMBGT(v int) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldRAMMB, v))
}

// RAMMBGTE applies the GTE predicate on the "ram_mb" field.
func RAMMBGTE(v int) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldRAMMB, v))
}

// RAMMBLT applies the LT predicate on the "ram_mb" field.
func RAMMBLT(v int) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldRAMMB, v))
}

// RAMMBLTE applies the LTE predicate on the "ram_mb" field.
func RAMMBLTE(v int) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldRAMMB, v))
}

// StorageGBEQ applies the EQ predicate on the "storage_gb" field.
func StorageGBEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldStorageGB, v))
}

// StorageGBNEQ applies the NEQ predicate on the "storage_gb" field.
func StorageGBNEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldStorageGB, v))
}

// StorageGBIn applies the In predicate on the "storage_gb" field.
func StorageGBIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldStorageGB, vs...))
}

// StorageGBNotIn applies the NotIn predicate on the "storage_gb" field.
func StorageGBNotIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldStorageGB, vs...))
}

// StorageGBGT applies the GT predicate on the "storage_gb" field.
func StorageGBGT(v int) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldStorageGB, v))
}

// StorageGBGTE applies the GTE predicate on the "storage_gb" field.
func StorageGBGTE(v int) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldStorageGB, v))
}

// StorageGBLT applies the LT predicate on the "storage_gb" field.
func StorageGBLT(v int) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldStorageGB, v))
}

// StorageGBLTE applies the LTE predicate on the "storage_gb" field.
func StorageGBLTE(v int) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldStorageGB, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldRegion, v))
}

// MaxRuntimeSecondsEQ applies the EQ predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsNEQ applies the NEQ predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsNEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsIn applies the In predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldMaxRuntimeSeconds, vs...))
}

// MaxRuntimeSecondsNotIn applies the NotIn predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsNotIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldMaxRuntimeSeconds, vs...))
}

// MaxRuntimeSecondsGT applies the GT predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsGT(v int) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsGTE applies the GTE predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsGTE(v int) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsLT applies the LT predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsLT(v int) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsLTE applies the LTE predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsLTE(v int) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldMaxRuntimeSeconds, v))
}

// IdleTimeoutSecondsEQ applies the EQ predicate on the "idle_timeout_seconds" field.
func IdleTimeoutSecondsEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldIdleTimeoutSeconds, v))
}

// IdleTimeoutSecondsNEQ applies the NEQ predicate on the "idle_timeout_seconds" field.
func IdleTimeoutSecondsNEQ(v int) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldIdleTimeoutSeconds, v))
}

// IdleTimeoutSecondsIn applies the In predicate on the "idle_timeout_seconds" field.
func IdleTimeoutSecondsIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldIdleTimeoutSeconds, vs...))
}

// IdleTimeoutSecondsNotIn applies the NotIn predicate on the "idle_timeout_seconds" field.
func IdleTimeoutSecondsNotIn(vs ...int) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldIdleTimeoutSeconds, vs...))
}

// IdleTimeoutSecondsGT applies the GT predicate on the "idle_timeout_seconds" field.
func IdleTimeoutSecondsGT(v int) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldIdleTimeoutSeconds, v))
}

// IdleTimeoutSecondsGTE applies the GTE predicate on the "idle_timeout_seconds" field.
func IdleTimeoutSecondsGTE(v int) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldIdleTimeoutSeconds, v))
}

// IdleTimeoutSecondsLT applies the LT predicate on the "idle_timeout_seconds" field.
func IdleTimeoutSecondsLT(v int) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldIdleTimeoutSeconds, v))
}

// IdleTimeoutSecondsLTE applies the LTE predicate on the "idle_timeout_seconds" field.
func IdleTimeoutSecondsLTE(v int) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldIdleTimeoutSeconds, v))
}

// AuthTokenEncryptedEQ applies the EQ predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedEQ(v []byte) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldAuthTokenEncrypted, v))
}

// AuthTokenEncryptedNEQ applies the NEQ predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedNEQ(v []byte) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldAuthTokenEncrypted, v))
}

// AuthTokenEncryptedIn applies the In predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedIn(vs ...[]byte) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldAuthTokenEncrypted, vs...))
}

// AuthTokenEncryptedNotIn applies the NotIn predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedNotIn(vs ...[]byte) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldAuthTokenEncrypted, vs...))
}

// AuthTokenEncryptedGT applies the GT predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedGT(v []byte) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldAuthTokenEncrypted, v))
}

// AuthTokenEncryptedGTE applies the GTE predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedGTE(v []byte) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldAuthTokenEncrypted, v))
}

// AuthTokenEncryptedLT applies the LT predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedLT(v []byte) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldAuthTokenEncrypted, v))
}

// AuthTokenEncryptedLTE applies the LTE predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedLTE(v []byte) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldAuthTokenEncrypted, v))
}

// AuthTokenEncryptedIsNil applies the IsNil predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldAuthTokenEncrypted))
}

// AuthTokenEncryptedNotNil applies the NotNil predicate on the "auth_token_encrypted" field.
func AuthTokenEncryptedNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldAuthTokenEncrypted))
}

// SecretsEncryptedEQ applies the EQ predicate on the "secrets_encrypted" field.
func SecretsEncryptedEQ(v []byte) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldSecretsEncrypted, v))
}

// SecretsEncryptedNEQ applies the NEQ predicate on the "secrets_encrypted" field.
func SecretsEncryptedNEQ(v []byte) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldSecretsEncrypted, v))
}

// SecretsEncryptedIn applies the In predicate on the "secrets_encrypted" field.
func SecretsEncryptedIn(vs ...[]byte) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldSecretsEncrypted, vs...))
}

// SecretsEncryptedNotIn applies the NotIn predicate on the "secrets_encrypted" field.
func SecretsEncryptedNotIn(vs ...[]byte) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldSecretsEncrypted, vs...))
}

// SecretsEncryptedGT applies the GT predicate on the "secrets_encrypted" field.
func SecretsEncryptedGT(v []byte) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldSecretsEncrypted, v))
}

// SecretsEncryptedGTE applies the GTE predicate on the "secrets_encrypted" field.
func SecretsEncryptedGTE(v []byte) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldSecretsEncrypted, v))
}

// SecretsEncryptedLT applies the LT predicate on the "secrets_encrypted" field.
func SecretsEncryptedLT(v []byte) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldSecretsEncrypted, v))
}

// SecretsEncryptedLTE applies the LTE predicate on the "secrets_encrypted" field.
func SecretsEncryptedLTE(v []byte) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldSecretsEncrypted, v))
}

// SecretsEncryptedIsNil applies the IsNil predicate on the "secrets_encrypted" field.
func SecretsEncryptedIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldSecretsEncrypted))
}

// SecretsEncryptedNotNil applies the NotNil predicate on the "secrets_encrypted" field.
func SecretsEncryptedNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldSecretsEncrypted))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldLastError, v))
}

// EndpointsIsNil applies the IsNil predicate on the "endpoints" field.
func EndpointsIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldEndpoints))
}

// EndpointsNotNil applies the NotNil predicate on the "endpoints" field.
func EndpointsNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldEndpoints))
}

// GpusEQ applies the EQ predicate on the "gpus" field.
func GpusEQ(v int32) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldGpus, v))
}

// GpusNEQ applies the NEQ predicate on the "gpus" field.
func GpusNEQ(v int32) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldGpus, v))
}

// GpusIn applies the In predicate on the "gpus" field.
func GpusIn(vs ...int32) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldGpus, vs...))
}

// GpusNotIn applies the NotIn predicate on the "gpus" field.
func GpusNotIn(vs ...int32) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldGpus, vs...))
}

// GpusGT applies the GT predicate on the "gpus" field.
func GpusGT(v int32) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldGpus, v))
}

// GpusGTE applies the GTE predicate on the "gpus" field.
func GpusGTE(v int32) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldGpus, v))
}

// GpusLT applies the LT predicate on the "gpus" field.
func GpusLT(v int32) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldGpus, v))
}

// GpusLTE applies the LTE predicate on the "gpus" field.
func GpusLTE(v int32) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldGpus, v))
}

// GpuKindEQ applies the EQ predicate on the "gpu_kind" field.
func GpuKindEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldGpuKind, v))
}

// GpuKindNEQ applies the NEQ predicate on the "gpu_kind" field.
func GpuKindNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldGpuKind, v))
}

// GpuKindIn applies the In predicate on the "gpu_kind" field.
func GpuKindIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldGpuKind, vs...))
}

// GpuKindNotIn applies the NotIn predicate on the "gpu_kind" field.
func GpuKindNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldGpuKind, vs...))
}

// GpuKindGT applies the GT predicate on the "gpu_kind" field.
func GpuKindGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldGpuKind, v))
}

// GpuKindGTE applies the GTE predicate on the "gpu_kind" field.
func GpuKindGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldGpuKind, v))
}

// GpuKindLT applies the LT predicate on the "gpu_kind" field.
func GpuKindLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldGpuKind, v))
}

// GpuKindLTE applies the LTE predicate on the "gpu_kind" field.
func GpuKindLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldGpuKind, v))
}

// GpuKindContains applies the Contains predicate on the "gpu_kind" field.
func GpuKindContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldGpuKind, v))
}

// GpuKindHasPrefix applies the HasPrefix predicate on the "gpu_kind" field.
func GpuKindHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldGpuKind, v))
}

// GpuKindHasSuffix applies the HasSuffix predicate on the "gpu_kind" field.
func GpuKindHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldGpuKind, v))
}

// GpuKindEqualFold applies the EqualFold predicate on the "gpu_kind" field.
func GpuKindEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldGpuKind, v))
}

// GpuKindContainsFold applies the ContainsFold predicate on the "gpu_kind" field.
func GpuKindContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldGpuKind, v))
}

// GpuProfileEQ applies the EQ predicate on the "gpu_profile" field.
func GpuProfileEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldGpuProfile, v))
}

// GpuProfileNEQ applies the NEQ predicate on the "gpu_profile" field.
func GpuProfileNEQ(v string) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldGpuProfile, v))
}

// GpuProfileIn applies the In predicate on the "gpu_profile" field.
func GpuProfileIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldGpuProfile, vs...))
}

// GpuProfileNotIn applies the NotIn predicate on the "gpu_profile" field.
func GpuProfileNotIn(vs ...string) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldGpuProfile, vs...))
}

// GpuProfileGT applies the GT predicate on the "gpu_profile" field.
func GpuProfileGT(v string) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldGpuProfile, v))
}

// GpuProfileGTE applies the GTE predicate on the "gpu_profile" field.
func GpuProfileGTE(v string) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldGpuProfile, v))
}

// GpuProfileLT applies the LT predicate on the "gpu_profile" field.
func GpuProfileLT(v string) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldGpuProfile, v))
}

// GpuProfileLTE applies the LTE predicate on the "gpu_profile" field.
func GpuProfileLTE(v string) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldGpuProfile, v))
}

// GpuProfileContains applies the Contains predicate on the "gpu_profile" field.
func GpuProfileContains(v string) predicate.VM {
	return predicate.VM(sql.FieldContains(FieldGpuProfile, v))
}

// GpuProfileHasPrefix applies the HasPrefix predicate on the "gpu_profile" field.
func GpuProfileHasPrefix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasPrefix(FieldGpuProfile, v))
}

// GpuProfileHasSuffix applies the HasSuffix predicate on the "gpu_profile" field.
func GpuProfileHasSuffix(v string) predicate.VM {
	return predicate.VM(sql.FieldHasSuffix(FieldGpuProfile, v))
}

// GpuProfileEqualFold applies the EqualFold predicate on the "gpu_profile" field.
func GpuProfileEqualFold(v string) predicate.VM {
	return predicate.VM(sql.FieldEqualFold(FieldGpuProfile, v))
}

// GpuProfileContainsFold applies the ContainsFold predicate on the "gpu_profile" field.
func GpuProfileContainsFold(v string) predicate.VM {
	return predicate.VM(sql.FieldContainsFold(FieldGpuProfile, v))
}

// GpuUuidsIsNil applies the IsNil predicate on the "gpu_uuids" field.
func GpuUuidsIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldGpuUuids))
}

// GpuUuidsNotNil applies the NotNil predicate on the "gpu_uuids" field.
func GpuUuidsNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldGpuUuids))
}

// MigInstanceUuidsIsNil applies the IsNil predicate on the "mig_instance_uuids" field.
func MigInstanceUuidsIsNil() predicate.VM {
	return predicate.VM(sql.FieldIsNull(FieldMigInstanceUuids))
}

// MigInstanceUuidsNotNil applies the NotNil predicate on the "mig_instance_uuids" field.
func MigInstanceUuidsNotNil() predicate.VM {
	return predicate.VM(sql.FieldNotNull(FieldMigInstanceUuids))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VM {
	return predicate.VM(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VM {
	return predicate.VM(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VM) predicate.VM {
	return predicate.VM(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VM) predicate.VM {
	return predicate.VM(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VM) predicate.VM {
	return predicate.VM(sql.NotPredicates(p))
}
