// regenerate src/version.ts from package.json so the runtime user-agent version
// always matches the published package version. runs as the prebuild hook.
import { readFileSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const body = `// generated by scripts/gen-version.mjs. do not edit.
export const VERSION = ${JSON.stringify(pkg.version)};
`;
writeFileSync(new URL("../src/version.ts", import.meta.url), body);
